import Foundation
import VeeCore

/// Puts the SDK where a plugin's interpreter will find it, so a plugin that
/// imports it runs without a copy of the SDK sitting beside it.
///
/// A Vee plugin is a single file with no build step, which used to mean the SDK
/// had to travel as a sibling — and a sibling is a shared, mutable, unversioned
/// dependency in a flat folder: one `vee.py` serving every plugin beside it,
/// whichever landed first, with no way to reconcile them. Vee already builds
/// the environment every plugin runs in, so it can simply *be* the place the
/// import resolves to.
///
/// Precedence is what makes this safe to adopt. Python searches the script's
/// own directory before `PYTHONPATH`, and a relative `./vee.ts` names a file
/// directly, so a folder that already vendors the SDK — a plugin repository's
/// checked-in copy, or an author pinning a version — keeps using its own and is
/// unaffected by anything here.
public enum SDKProvisioner {
    /// Written into `root`, whose contents are Vee's to manage.
    public static let pythonSubdirectory = "python"
    public static let nodeSubdirectory = "node"
    public static let resolverName = "vee-resolver.mjs"

    /// The Node hook that answers a bare `@navbytes/vee` import.
    ///
    /// `NODE_PATH` is ignored by ESM, so a bare specifier cannot be satisfied
    /// by pointing at a directory — it needs a resolver. `registerHooks` is the
    /// current, non-deprecated form (`module.register` warns as of DEP0205),
    /// and it short-circuits only the specifiers Vee owns, delegating every
    /// other import untouched.
    ///
    /// The SDK path arrives through the environment rather than being baked in,
    /// so this file is identical on every machine and a moved support directory
    /// needs no rewrite.
    static let resolverSource = """
    // Generated by Vee — resolves the Vee SDK for plugins that import it by
    // package name. Do not edit; it is rewritten whenever Vee starts.
    import { registerHooks } from "node:module";
    import { pathToFileURL } from "node:url";

    const sdk = process.env.VEE_SDK_TS;

    registerHooks({
      resolve(specifier, context, next) {
        if (sdk && (specifier === "@navbytes/vee" || specifier === "vee")) {
          return { url: pathToFileURL(sdk).href, shortCircuit: true };
        }
        return next(specifier, context);
      },
    });

    """

    /// Materializes the SDKs and the resolver under `root`, returning it, or nil
    /// if nothing could be written.
    ///
    /// Content-compared rather than blindly rewritten so an upgrade replaces a
    /// stale copy while an unchanged one costs a read. Best-effort throughout:
    /// a plugin that vendors its own SDK, or prints the format directly, does
    /// not need any of this to exist, so failing to write it must never stop a
    /// plugin from running.
    @discardableResult
    public static func provision(into root: String, fileManager: FileManager = .default) -> String? {
        guard let python = EmbeddedSDK.source(for: "python"),
              let typescript = EmbeddedSDK.source(for: "typescript")
        else { return nil }
        let pythonDir = (root as NSString).appendingPathComponent(pythonSubdirectory)
        let nodeDir = (root as NSString).appendingPathComponent(nodeSubdirectory)
        do {
            try fileManager.createDirectory(atPath: pythonDir, withIntermediateDirectories: true)
            try fileManager.createDirectory(atPath: nodeDir, withIntermediateDirectories: true)
        } catch {
            return nil
        }
        write(python, to: (pythonDir as NSString).appendingPathComponent("vee.py"))
        write(typescript, to: (nodeDir as NSString).appendingPathComponent("vee.ts"))
        write(resolverSource, to: (nodeDir as NSString).appendingPathComponent(resolverName))
        return root
    }

    private static func write(_ contents: String, to path: String) {
        if let existing = try? String(contentsOfFile: path, encoding: .utf8), existing == contents { return }
        try? contents.write(toFile: path, atomically: true, encoding: .utf8)
    }

    /// Vee's own support directory for the SDKs, shared by the app and the
    /// CLI so `vee render` and a menu-bar refresh resolve the same import the
    /// same way. A plugin behaving differently under the tool its author
    /// debugs with than under the app its users run is the exact
    /// inconsistency this whole change exists to remove.
    public static var defaultRoot: String {
        let support = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory()).appendingPathComponent("Library/Application Support")
        return support.appendingPathComponent("Vee/sdk").path
    }

    /// `env` with the SDK reachable from it: Python's search path extended, and
    /// Node's resolver hook loaded.
    ///
    /// Both are *prepended* to whatever the user already had, never replacing
    /// it — someone's own `PYTHONPATH`, or a plugin's own `NODE_OPTIONS`, has
    /// to survive, and an entry of theirs that resolves the same name should
    /// keep winning.
    public static func apply(to env: [String: String], root: String) -> [String: String] {
        var env = env
        env["PYTHONPATH"] = prepend(pythonPath(in: root), to: env["PYTHONPATH"], separator: ":")
        if let importURL = nodeImportURL(in: root) {
            env["NODE_OPTIONS"] = prepend("--import \(importURL)", to: env["NODE_OPTIONS"], separator: " ")
            env["VEE_SDK_TS"] = typescriptPath(in: root)
        }
        return env
    }

    private static func prepend(_ value: String, to existing: String?, separator: String) -> String {
        guard let existing, !existing.isEmpty else { return value }
        return value + separator + existing
    }

    /// `PYTHONPATH` entry for the provisioned Python SDK.
    public static func pythonPath(in root: String) -> String {
        (root as NSString).appendingPathComponent(pythonSubdirectory)
    }

    /// The TypeScript SDK's own path, handed to the resolver as `VEE_SDK_TS`.
    public static func typescriptPath(in root: String) -> String {
        ((root as NSString).appendingPathComponent(nodeSubdirectory) as NSString).appendingPathComponent("vee.ts")
    }

    /// The `--import` argument for `NODE_OPTIONS`, as a percent-encoded file
    /// URL.
    ///
    /// A bare path would be wrong here: `NODE_OPTIONS` is split on whitespace,
    /// and the support directory this normally lives under is
    /// `Application Support` — a path with a space in it, which silently breaks
    /// the flag. A file URL encodes the space and needs no quoting.
    public static func nodeImportURL(in root: String) -> String? {
        let path = ((root as NSString).appendingPathComponent(nodeSubdirectory) as NSString)
            .appendingPathComponent(resolverName)
        return URL(fileURLWithPath: path).absoluteString
    }
}
