version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  patterns:
  - '*'
  multi-ecosystem-group: routine
- package-ecosystem: npm
  directory: /docs-site
  open-pull-requests-limit: 3
  patterns:
  - '*'
  multi-ecosystem-group: routine
multi-ecosystem-groups:
  routine:
    schedule:
      interval: weekly
