// Generated by scripts/embed_sdk.py — DO NOT EDIT.
//
// The SDK sources, embedded so `vee new` and `vee sdk` can write the SDK
// next to a plugin. A Vee plugin is a single executable with no build step,
// so the SDK travels with it as a sibling file rather than being resolved
// from a package manager.
//
// Regenerate with: python3 scripts/embed_sdk.py

enum EmbeddedSDK {
    /// The filename each language's SDK is written as, beside the plugin.
    static func filename(for language: String) -> String? {
        switch language {
        case "typescript": return "vee.ts"
        case "python": return "vee.py"
        default: return nil
        }
    }

    /// The SDK source for `language`, or nil when it does not vendor one.
    static func source(for language: String) -> String? {
        switch language {
        case "typescript": return typescript
        case "python": return python
        default: return nil
        }
    }

    static let typescript = #"""
// Vee plugin SDK — typed builders that emit the xbar/SwiftBar text format Vee
// parses. Zero dependencies; runs directly on Node (which strips the types).

export type Color = string;

export interface ItemOptions {
  color?: Color;
  size?: number;
  font?: string;
  length?: number;
  /** Trim surrounding whitespace from the text. */
  trim?: boolean;
  /** Interpret ANSI colour escapes in the text. */
  ansi?: boolean;
  /** Expand `:emoji:` shortcodes in the text. */
  emojize?: boolean;
  href?: string;
  /** Shell command to run on click; `params` become param1..N. */
  shell?: string;
  params?: string[];
  terminal?: boolean;
  refresh?: boolean;
  /** Show this line in the dropdown only, never in the menu bar. */
  dropdown?: boolean;
  alternate?: boolean;
  disabled?: boolean;
  checked?: boolean;
  key?: string;
  tooltip?: string;
  /** An image for the row: a base64 payload or a file path. */
  image?: string;
  /** Like `image`, but rendered as a template image (adapts to the theme). */
  templateImage?: string;
  /** SF Symbol name (SwiftBar/Vee extension). */
  sfimage?: string;
  /**
   * SF Symbol colour(s) → `sfcolor=`. A list supplies one colour per layer of
   * a multicolour symbol; Vee reads it as a comma-separated list, so keep
   * commas out of colour names.
   */
  sfColor?: Color | Color[];
  /** SF Symbol point size → `sfsize=`. */
  sfSize?: number;
  /** SF Symbol configuration string → `sfconfig=`. */
  sfConfig?: string;
  /** Render the text as inline Markdown. */
  md?: boolean;
  /** Trailing badge chip. */
  badge?: string;
  /** Render `:sf.symbol:` tokens in the text as inline SF Symbols. */
  symbolize?: boolean;
  /** Open this web URL in a web view on click → `webview=`. */
  webview?: string;
  /** Web view width in points → `webvieww=`. */
  webviewW?: number;
  /** Web view height in points → `webviewh=`. */
  webviewH?: number;
  /** Name of a macOS Shortcut to run on click → `shortcut=`. */
  shortcut?: string;
  /**
   * Render as a native, non-interactive section header (`header=true`) — a
   * real `NSMenuItem.sectionHeader`, not a disabled row dressed up as one.
   */
  header?: boolean;
  /**
   * Which edge this row's visual accessory anchors to → `accessory=`. Applies
   * uniformly to `sparkline`, `progress`, and the `chart` shapes, since they
   * share the same in-row geometry. Omitted, the accessory sits trailing.
   */
  accessory?: "leading" | "trailing";
  /** Inline data series → `sparkline=1,2,3`. */
  sparkline?: number[];
  /**
   * Sparkline width in points. `"full"` stretches the chart to the row's own
   * width instead. Emitted as `accessoryw=`, which sizes whichever accessory a
   * row carries; `progressW`, `chart.w` and `accessoryW` are the same knob
   * reached from different option sets.
   */
  sparklineW?: number | "full";

  /**
   * Width in points for whichever accessory this row carries — gauge,
   * sparkline, chart, or slider → `accessoryw=`. `"full"` stretches it to the
   * row's own width. Use this to size a `slider`, which has no option of its
   * own; for the others the per-accessory options are equivalent.
   */
  accessoryW?: number | "full";

  /** Height in points for this row's accessory → `accessoryh=`. Ignored for a toggle or slider. */
  accessoryH?: number;
  /** Sparkline height in points → `sparklineh=`. */
  sparklineH?: number;
  /** Sparkline line colour → `sparklinecolor=`. Falls back to the row's `color`. */
  sparklineColor?: Color;
  /** On/off switch → `toggle=on` / `toggle=off`. */
  toggle?: boolean;
  /** Continuous control → `slider=min,max,value`. */
  slider?: { min: number; max: number; value: number };
  /**
   * Progress gauge. Pass a fraction directly → `progress=<fraction>`, or
   * `{ value, max }` → `progress=<value>,<max>`, which the format accepts
   * natively and Vee divides on parse. The two-argument form keeps the
   * author's own numbers on the wire instead of a pre-divided float.
   */
  progress?: number | { value: number; max: number };
  /** Progress track (background) colour → `progresstrackcolor=`. */
  progressTrackColor?: Color;
  /**
   * @deprecated The pre-v2 spelling of `progressTrackColor`. Still accepted and
   * still emitted as `progresstrackcolor=`; will be removed in the next major
   * version.
   */
  trackColor?: Color;
  /**
   * Progress bar width in points, emitted as `accessoryw=`. `"full"` stretches the bar to
   * the row's own width instead, the same knob `chart.w` takes.
   */
  progressW?: number | "full";
  /** Progress bar height in points → `progressh=`. */
  progressH?: number;
  /**
   * Categorical share chart → `pie=` / `donut=` / `stackedbar=`. All three
   * shapes take the same data — one series of non-negative values read as
   * shares of a whole — so switching `kind` needs no other change.
   *
   * `labels`/`colors` are positional against `values`. Vee reads both as
   * comma-separated lists, so a label containing a comma would be read as two
   * labels: keep commas out of segment names.
   */
  chart?: {
    kind: "pie" | "donut" | "stackedbar";
    values: number[];
    labels?: string[];
    colors?: Color[];
    /**
     * Inline size in points, emitted as `accessoryw=`/`accessoryh=`. A pie/donut is a circle, so
     * either knob sizes both sides; a stacked bar takes them independently.
     * Omitted, a chart takes its per-kind default (24pt circle, 110×12 bar).
     * `w: "full"` stretches the chart to the row's own width instead — a
     * stacked bar only, since a circle has no free width (Vee warns and falls
     * back to points on `pie`/`donut`).
     */
    w?: number | "full";
    h?: number;
  };
}

// Vee's parser (LineParser.splitTextAndParams/parseParams) reads `\|`, `\n`,
// and `\\` as escapes — for a literal `|` (which would otherwise be read as
// the text/params delimiter) and a literal newline (which would otherwise
// split a plugin's single stdout line into two corrupted ones). Order matters:
// backslashes must be escaped first, or the backslash `escapeText` inserts for
// `|`/newline would itself get re-escaped.
function escapeText(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\n/g, "\\n");
}

// The characters that force a value through the quoted path. `\s` here is the
// reference definition the Python and Go SDKs mirror explicitly — each
// language's own "whitespace" class differs at the edges (Python's adds
// U+001C–U+001F, Go's `unicode.IsSpace` omits U+FEFF), so the set is written
// out there rather than inherited.
const NEEDS_QUOTE = /[\s|\\]/;

function quote(value: string): string {
  const escaped = escapeText(value);
  // Backslash also forces quoting: an unquoted (bare) value is never
  // unescaped by the parser, so anything containing an escape must go through
  // the quoted path, which is.
  //
  // A leading quote character forces it too: the parser decides a value is
  // quoted by looking at its first character, so emitting `"a"` bare would
  // round-trip back as `a` with the quotes eaten. Values that merely *contain*
  // a quote are safe bare — only the first position is read as a delimiter.
  if (NEEDS_QUOTE.test(value) || value.startsWith('"') || value.startsWith("'")) {
    return `"${escaped.replace(/"/g, '\\"')}"`;
  }
  return escaped;
}

function encode(options?: ItemOptions): string {
  if (!options) return "";
  const parts: string[] = [];
  const push = (key: string, value: unknown) => {
    if (value !== undefined && value !== null) parts.push(`${key}=${quote(String(value))}`);
  };
  push("color", options.color);
  push("size", options.size);
  push("font", options.font);
  push("length", options.length);
  push("trim", options.trim);
  push("ansi", options.ansi);
  push("emojize", options.emojize);
  push("href", options.href);
  if (options.shell !== undefined) {
    push("shell", options.shell);
    (options.params ?? []).forEach((p, i) => push(`param${i + 1}`, p));
  }
  push("terminal", options.terminal);
  push("refresh", options.refresh);
  push("dropdown", options.dropdown);
  push("alternate", options.alternate);
  push("disabled", options.disabled);
  push("checked", options.checked);
  push("key", options.key);
  push("tooltip", options.tooltip);
  push("image", options.image);
  push("templateimage", options.templateImage);
  push("sfimage", options.sfimage);
  if (options.sfColor !== undefined) {
    push("sfcolor", Array.isArray(options.sfColor) ? options.sfColor.join(",") : options.sfColor);
  }
  push("sfsize", options.sfSize);
  push("sfconfig", options.sfConfig);
  push("md", options.md);
  push("badge", options.badge);
  push("symbolize", options.symbolize);
  push("webview", options.webview);
  push("webvieww", options.webviewW);
  push("webviewh", options.webviewH);
  push("shortcut", options.shortcut);
  push("header", options.header);
  push("accessory", options.accessory);
  if (options.sparkline !== undefined) push("sparkline", options.sparkline.map(String).join(","));
  push("sparklinecolor", options.sparklineColor);
  if (options.toggle !== undefined) push("toggle", options.toggle ? "on" : "off");
  if (options.slider !== undefined) {
    const s = options.slider;
    push("slider", `${s.min},${s.max},${s.value}`);
  }
  if (options.progress !== undefined) {
    const p = options.progress;
    push("progress", typeof p === "number" ? String(p) : `${p.value},${p.max}`);
  }
  push("progresstrackcolor", options.progressTrackColor ?? options.trackColor);
  if (options.chart !== undefined) {
    const c = options.chart;
    push(c.kind, c.values.map(String).join(","));
    if (c.labels !== undefined) push("chartlabels", c.labels.join(","));
    if (c.colors !== undefined) push("chartcolors", c.colors.join(","));
  }
  // One wire parameter sizes whichever accessory the row carries, so the
  // per-accessory options above all funnel here. They stay separate in the API
  // because a typed builder already knows which accessory you are describing —
  // the ambiguity `accessoryw=` solves for hand-written lines cannot arise.
  push("accessoryw", options.accessoryW ?? options.sparklineW ?? options.progressW ?? options.chart?.w);
  push("accessoryh", options.accessoryH ?? options.sparklineH ?? options.progressH ?? options.chart?.h);
  return parts.length ? " | " + parts.join(" ") : "";
}

/** A menu section at a given submenu depth (0 = top level). */
export class Section {
  private readonly lines: string[];
  private readonly depth: number;

  constructor(lines: string[], depth: number) {
    this.lines = lines;
    this.depth = depth;
  }

  private prefix(): string {
    return "-".repeat(this.depth * 2);
  }

  item(text: string, options?: ItemOptions): this {
    this.lines.push(this.prefix() + escapeText(text) + encode(options));
    return this;
  }

  separator(): this {
    this.lines.push(this.prefix() + "---");
    return this;
  }

  /** Adds an item and returns a `Section` for its submenu. */
  submenu(text: string, options?: ItemOptions): Section {
    this.item(text, options);
    return new Section(this.lines, this.depth + 1);
  }
}

/** The top-level menu: title line(s) plus a dropdown. */
export class Menu {
  private readonly titles: string[] = [];
  private readonly body: string[] = [];

  title(text: string, options?: ItemOptions): this {
    this.titles.push(escapeText(text) + encode(options));
    return this;
  }

  get dropdown(): Section {
    return new Section(this.body, 0);
  }

  toString(): string {
    const head = this.titles.join("\n");
    return this.body.length ? `${head}\n---\n${this.body.join("\n")}` : head;
  }

  print(): void {
    process.stdout.write(this.toString() + "\n");
  }
}

// ---------------------------------------------------------------------------
// Widget surface contract — the rich JSON payload a plugin prints to stdout
// when invoked with VEE_TARGET=widget, instead of the xbar/SwiftBar text
// format above. See docs/design/widget-surface-contract.md §4.

export type WidgetTemplate = "stat" | "gauge" | "trend" | "list" | "board";
export type WidgetStatus = "ok" | "warning" | "error";
export type WidgetActionKind = "refresh" | "href" | "shortcut";

export interface WidgetCardItem {
  label: string;
  value?: string;
  symbol?: string;
  tint?: Color;
}

export interface WidgetCardAction {
  kind: WidgetActionKind;
  label: string;
  /** The URL to open, for `kind: "href"`. Scheme-filtered by Vee on parse. */
  url?: string;
  /** The Shortcut name to run, for `kind: "shortcut"`. */
  name?: string;
}

export interface WidgetCardOptions {
  template?: WidgetTemplate;
  title?: string;
  /** SF Symbol name for the glyph. */
  symbol?: string;
  tint?: Color;
  /** The headline value, already formatted (e.g. `"$18.2k"`). */
  value?: string;
  caption?: string;
  detail?: string;
  status?: WidgetStatus;
  /** `0…1`; clamped by Vee if out of range. */
  progress?: number;
  trend?: number[];
  /** Rows for the `list`/`board` templates. */
  items?: WidgetCardItem[];
  /** Up to two are rendered as buttons; the templates decide which. */
  actions?: WidgetCardAction[];
  /** Seconds — a hint for the next widget reload. */
  refreshAfter?: number;
  /** Seconds — when the tile should show a stale treatment. */
  staleAfter?: number;
  /**
   * An optional composable **layout tree** — the escape hatch alongside the
   * five preset templates, for layouts the presets can't express (two columns,
   * a date rail, activity rings, a KPI grid). Build it with the node helpers
   * (`VStack`/`HStack`/`Text`/`Image`/`Gauge`/…). When present, Vee renders the
   * tree instead of `template`. See docs/design/widget-surface-contract.md.
   */
  layout?: WidgetNode;
}

// ── Layout tree ──────────────────────────────────────────────────────────────
// A bounded, native primitive tree (no freeform drawing). Each node maps to one
// SwiftUI primitive; Vee sanitizes/caps the tree on parse (depth 8, ≤64 nodes,
// text ≤512, sparkline ≤256, numeric clamps). Node keys are emitted in a fixed
// canonical order so the three SDKs produce byte-identical output.

/** A font token, or an explicit point size (clamped 8…96) when a token won't fit. */
export interface NodeFont {
  size?: "caption2" | "caption" | "footnote" | "subheadline" | "body" | "headline" | "title3" | "title2" | "title" | "largeTitle";
  pointSize?: number;
  weight?: "regular" | "medium" | "semibold" | "bold";
  design?: "default" | "rounded" | "monospaced" | "serif";
}

/** Per-element modifiers. Only bounded, SwiftUI-cheap options are exposed. */
export interface NodeStyle {
  font?: NodeFont;
  tint?: Color;
  /** Multiline text alignment. */
  align?: "leading" | "center" | "trailing";
  /** Uniform padding in points (clamped 0…64). */
  padding?: number;
  /** Maximum text lines (clamped 1…20). */
  lineLimit?: number;
  /** Keep numeric columns from jittering. */
  monospacedDigit?: boolean;
  /** Let a headline shrink to fit rather than truncate (clamped 0.3…1). */
  minScale?: number;
  /** Grow to fill available width (the only, bounded, width control). */
  fill?: boolean;
}

export type NodeType =
  | "vstack" | "hstack" | "zstack" | "grid"
  | "text" | "image" | "gauge" | "sparkline" | "spacer" | "divider";

export interface WidgetNode {
  type: NodeType;
  text?: string;
  /** SF Symbol name, for an `image` node (v1 renders SF Symbols only). */
  symbol?: string;
  /** `0…1` fill, for a `gauge` node. */
  value?: number;
  /** Series, for a `sparkline` node. */
  values?: number[];
  /** `"linear"` (default) or `"circular"`, for a `gauge` node. */
  gaugeStyle?: "linear" | "circular";
  /** Cross-axis alignment, for a container. */
  align?: string;
  /** Inter-child spacing, for a container. */
  spacing?: number;
  /** Column count, for a `grid` (default 2; clamped 1…4). */
  columns?: number;
  /** Minimum length, for a `spacer`. */
  minLength?: number;
  /** Families this node renders in (`small`/`medium`/`large`); absent = all. */
  families?: Array<"small" | "medium" | "large">;
  style?: NodeStyle;
  children?: WidgetNode[];
}

/**
 * The widget-mode payload (see `WidgetCardOptions`). Call `.toString()`/
 * `.print()` exactly once per `VEE_TARGET=widget` run with the richest data
 * available — each native template (small/medium/large) takes what fits.
 */
export class WidgetCard {
  private readonly options: WidgetCardOptions;

  constructor(options: WidgetCardOptions = {}) {
    this.options = options;
  }

  toString(): string {
    const o = this.options;
    const payload: Record<string, unknown> = { vee_widget: 1 };
    const push = (key: string, value: unknown) => {
      if (value !== undefined) payload[key] = value;
    };
    push("template", o.template);
    push("title", o.title);
    push("symbol", o.symbol);
    push("tint", o.tint);
    push("value", o.value);
    push("caption", o.caption);
    push("detail", o.detail);
    push("status", o.status);
    push("progress", o.progress);
    push("trend", o.trend);
    push("items", o.items);
    push("actions", o.actions);
    push("refresh_after", o.refreshAfter);
    push("stale_after", o.staleAfter);
    push("layout", o.layout ? orderNode(o.layout) : undefined);
    return JSON.stringify(payload);
  }

  print(): void {
    process.stdout.write(this.toString() + "\n");
  }
}

/** Builds a widget card. Equivalent to `new WidgetCard(options)`. */
export function widgetCard(options?: WidgetCardOptions): WidgetCard {
  return new WidgetCard(options);
}

// ── Layout node serialization + builders ─────────────────────────────────────

/** Rebuilds a node with keys in the canonical order the three SDKs share, so
 *  output is byte-identical regardless of how the node object was constructed.
 *  `undefined` keys are dropped; `0`/`false` are kept. */
function orderNode(n: WidgetNode): Record<string, unknown> {
  const o: Record<string, unknown> = {};
  const put = (k: string, v: unknown) => { if (v !== undefined) o[k] = v; };
  put("type", n.type);
  put("text", n.text);
  put("symbol", n.symbol);
  put("value", n.value);
  put("values", n.values);
  put("gauge_style", n.gaugeStyle);
  put("align", n.align);
  put("spacing", n.spacing);
  put("columns", n.columns);
  put("min_length", n.minLength);
  put("families", n.families);
  put("style", n.style ? orderStyle(n.style) : undefined);
  put("children", n.children ? n.children.map(orderNode) : undefined);
  return o;
}

function orderStyle(s: NodeStyle): Record<string, unknown> {
  const o: Record<string, unknown> = {};
  const put = (k: string, v: unknown) => { if (v !== undefined) o[k] = v; };
  put("font", s.font ? orderFont(s.font) : undefined);
  put("tint", s.tint);
  put("align", s.align);
  put("padding", s.padding);
  put("line_limit", s.lineLimit);
  put("monospaced_digit", s.monospacedDigit);
  put("min_scale", s.minScale);
  put("fill", s.fill);
  return o;
}

function orderFont(f: NodeFont): Record<string, unknown> {
  const o: Record<string, unknown> = {};
  const put = (k: string, v: unknown) => { if (v !== undefined) o[k] = v; };
  put("size", f.size);
  put("point_size", f.pointSize);
  put("weight", f.weight);
  put("design", f.design);
  return o;
}

type ContainerOpts = { align?: string; spacing?: number; families?: WidgetNode["families"]; style?: NodeStyle };
type LeafOpts = { families?: WidgetNode["families"]; style?: NodeStyle };

/**
 * Builders for the layout tree. Namespaced (`Node.VStack(…)`) so they don't
 * collide with the card-level template builders (`Stat`/`Gauge`/…) and stay
 * clearly node-level. Each returns a `WidgetNode`; `widgetCard({ layout })`
 * serializes it in the canonical key order the three SDKs share.
 */
export const Node = {
  /** A vertical stack. */
  VStack: (children: WidgetNode[], opts: ContainerOpts = {}): WidgetNode => ({ type: "vstack", children, ...opts }),
  /** A horizontal stack — side-by-side regions (two columns, a date rail, a row of cells). */
  HStack: (children: WidgetNode[], opts: ContainerOpts = {}): WidgetNode => ({ type: "hstack", children, ...opts }),
  /** A depth stack — overlays and rings (e.g. concentric gauges). */
  ZStack: (children: WidgetNode[], opts: ContainerOpts = {}): WidgetNode => ({ type: "zstack", children, ...opts }),
  /** A grid of `columns` (default 2, clamped 1…4) — KPI boards. */
  Grid: (children: WidgetNode[], opts: ContainerOpts & { columns?: number } = {}): WidgetNode => ({ type: "grid", children, ...opts }),
  /** A text run. */
  Text: (text: string, opts: LeafOpts = {}): WidgetNode => ({ type: "text", text, ...opts }),
  /** An SF Symbol glyph (v1 renders SF Symbols only). */
  Image: (symbol: string, opts: LeafOpts = {}): WidgetNode => ({ type: "image", symbol, ...opts }),
  /** A gauge — `linear` (default) or `circular`. `value` is `0…1`. */
  Gauge: (value: number, opts: { gaugeStyle?: "linear" | "circular" } & LeafOpts = {}): WidgetNode => ({ type: "gauge", value, ...opts }),
  /** A dependency-free line chart from `values`. */
  Sparkline: (values: number[], opts: LeafOpts = {}): WidgetNode => ({ type: "sparkline", values, ...opts }),
  /** Flexible empty space. */
  Spacer: (opts: { minLength?: number; families?: WidgetNode["families"] } = {}): WidgetNode => ({ type: "spacer", ...opts }),
  /** A hairline divider. */
  Divider: (opts: { families?: WidgetNode["families"] } = {}): WidgetNode => ({ type: "divider", ...opts }),
};

type TemplatelessOptions = Omit<WidgetCardOptions, "template">;

/** Glyph, big `value` in `tint`, `title`/`caption`. The default template. */
export function Stat(options: TemplatelessOptions): WidgetCard {
  return new WidgetCard({ ...options, template: "stat" });
}

/** Stat + a native gauge from `progress`. */
export function Gauge(options: TemplatelessOptions): WidgetCard {
  return new WidgetCard({ ...options, template: "gauge" });
}

/** Stat + a sparkline from `trend`. */
export function Trend(options: TemplatelessOptions): WidgetCard {
  return new WidgetCard({ ...options, template: "trend" });
}

/** `title` header + `items` as rows. */
export function List(options: TemplatelessOptions): WidgetCard {
  return new WidgetCard({ ...options, template: "list" });
}

/** A compact grid of `items` as stat cells (KPI board). */
export function Board(options: TemplatelessOptions): WidgetCard {
  return new WidgetCard({ ...options, template: "board" });
}

// ---------------------------------------------------------------------------
// Structured-JSON output — the optional alternative to the text protocol above.
// A plugin opts in by printing a single `{"vee":1,…}` object; Vee decodes it
// directly, with no line parsing, no `|`-separated parameters and no quoting
// rules. See docs/_content/json-output.md.
//
// `JSONMenu` deliberately mirrors `Menu` method for method — `title`,
// `dropdown`, `item`, `separator`, `submenu`, `toString`, `print` — so choosing
// a wire format does not mean learning a second builder.

/** Options for a JSON menu item.
 *
 * The JSON protocol carries a subset of the text protocol's parameters, so this
 * is a distinct type rather than `ItemOptions`: an option JSON cannot express
 * is a compile error here, not a key that is silently dropped on the way out.
 */
export interface JSONItemOptions {
  color?: Color;
  size?: number;
  href?: string;
  shell?: string;
  params?: string[];
  terminal?: boolean;
  refresh?: boolean;
  sfimage?: string;
  disabled?: boolean;
  checked?: boolean;
  tooltip?: string;
  header?: boolean;
  accessory?: "leading" | "trailing";
  sparkline?: number[];
  /** Sparkline width in points; `"full"` stretches it to the row's width. */
  /** @deprecated Use `accessoryWidth`. */
  sparklineWidth?: number | "full";
  /** Width for whichever accessory this item carries, or `"full"`. */
  accessoryWidth?: number | "full";
  /** Height for whichever accessory this item carries. */
  accessoryHeight?: number;
  sparklineHeight?: number;
  sparklineColor?: Color;
  toggle?: boolean;
  slider?: { min: number; max: number; value: number };
  /** A completion fraction, clamped to `0…1` by Vee. */
  progress?: number;
  progressTrackColor?: Color;
  /** Progress bar width in points; `"full"` stretches it to the row's width. */
  progressWidth?: number | "full";
  progressHeight?: number;
  chart?: {
    kind: "pie" | "donut" | "stackedbar";
    values: number[];
    labels?: string[];
    colors?: Color[];
    w?: number | "full";
    h?: number;
  };
  /** An alternate row, shown while ⌥ is held. */
  alternate?: JSONItem;
}

/** One item in a JSON menu: `JSONItemOptions` plus the structural keys. */
export interface JSONItem extends JSONItemOptions {
  text?: string;
  separator?: boolean;
  submenu?: JSONItem[];
}

// The key order every SDK emits, so the three produce byte-identical JSON.
const JSON_ITEM_KEYS: Array<keyof JSONItem> = [
  "text", "separator", "color", "size", "href", "shell", "params", "terminal",
  "refresh", "sfimage", "disabled", "checked", "tooltip", "header", "accessory",
  "sparkline", "sparklineWidth", "sparklineHeight", "sparklineColor",
  "accessoryWidth", "accessoryHeight",
  "toggle", "slider", "progress", "progressTrackColor", "progressWidth",
  "progressHeight", "chart", "submenu", "alternate",
];

/** Rebuilds an item with keys in the shared canonical order, dropping absent
 *  ones and recursing into `submenu`/`alternate`. */
function orderJSONItem(item: JSONItem): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const key of JSON_ITEM_KEYS) {
    const value = item[key];
    if (value === undefined) continue;
    if (key === "submenu") out[key] = (value as JSONItem[]).map(orderJSONItem);
    else if (key === "alternate") out[key] = orderJSONItem(value as JSONItem);
    else out[key] = value;
  }
  return out;
}

/** A JSON menu section at a given submenu depth. Mirrors `Section`. */
export class JSONSection {
  private readonly items: JSONItem[];

  constructor(items: JSONItem[]) {
    this.items = items;
  }

  item(text: string, options?: JSONItemOptions): this {
    this.items.push({ text, ...options });
    return this;
  }

  separator(): this {
    this.items.push({ separator: true });
    return this;
  }

  /** Adds an item and returns a `JSONSection` for its submenu. */
  submenu(text: string, options?: JSONItemOptions): JSONSection {
    const submenu: JSONItem[] = [];
    this.items.push({ text, ...options, submenu });
    return new JSONSection(submenu);
  }
}

/** The top-level JSON menu: title line(s) plus a dropdown. Mirrors `Menu`. */
export class JSONMenu {
  private readonly titles: JSONItem[] = [];
  private readonly body: JSONItem[] = [];

  title(text: string, options?: JSONItemOptions): this {
    this.titles.push({ text, ...options });
    return this;
  }

  get dropdown(): JSONSection {
    return new JSONSection(this.body);
  }

  toString(): string {
    const payload: Record<string, unknown> = { vee: 1, title: this.titles.map(orderJSONItem) };
    if (this.body.length) payload.items = this.body.map(orderJSONItem);
    return JSON.stringify(payload);
  }

  print(): void {
    process.stdout.write(this.toString() + "\n");
  }
}
"""#

    static let python = #"""
"""Vee plugin SDK — typed builders that emit the xbar/SwiftBar text format Vee
parses. Zero dependencies; pure standard-library Python.

Mirrors the TypeScript SDK (``plugins/typescript/vee.ts``): the same builder shape,
option names, encoding order, and quoting, so a plugin reads the same in either
language and both produce byte-identical output for the same menu.
"""

from __future__ import annotations

import json
import sys
import warnings
from typing import Any

__all__ = ["Menu", "Section", "JSONMenu", "JSONSection", "WidgetCard", "widget_card",
           "Stat", "Gauge", "Trend", "List", "Board"]

# The characters that force a value through the quoted path: JavaScript's `\s`
# set (the reference the three SDKs share), plus the two the format itself
# reserves. Spelled out by code point rather than borrowed from Python's own
# `\s`, which additionally matches U+001C-U+001F and U+0085 and does not match
# U+FEFF -- close enough to look right, different enough to break
# byte-identical output.
_QUOTE_FORCING = frozenset(
    "\t\n\v\f\r \u00a0\u1680\u2028\u2029\u202f\u205f\u3000\ufeff|\\"
) | frozenset(chr(c) for c in range(0x2000, 0x200B))


def _needs_quote(value: str) -> bool:
    return any(ch in _QUOTE_FORCING for ch in value)


# Option name -> emitted key, in the exact order the TypeScript SDK emits them.
# ``shell`` is handled specially (it pulls in param1..N), so it is not listed.
_SCALAR_KEYS: list[tuple[str, str]] = [
    ("color", "color"),
    ("size", "size"),
    ("font", "font"),
    ("length", "length"),
    ("trim", "trim"),
    ("ansi", "ansi"),
    ("emojize", "emojize"),
    ("href", "href"),
]

_TRAILING_KEYS: list[tuple[str, str]] = [
    ("terminal", "terminal"),
    ("refresh", "refresh"),
    ("dropdown", "dropdown"),
    ("alternate", "alternate"),
    ("disabled", "disabled"),
    ("checked", "checked"),
    ("key", "key"),
    ("tooltip", "tooltip"),
    ("image", "image"),
    ("template_image", "templateimage"),
    ("sfimage", "sfimage"),
    # sfcolor is emitted here too -- see the branch in _encode; it accepts a
    # list as well as a scalar, so it cannot ride this plain key table.
    ("sf_size", "sfsize"),
    ("sf_config", "sfconfig"),
    ("md", "md"),
    ("badge", "badge"),
    ("symbolize", "symbolize"),
    ("webview", "webview"),
    ("webview_w", "webvieww"),
    ("webview_h", "webviewh"),
    ("shortcut", "shortcut"),
    ("header", "header"),
    ("accessory", "accessory"),
]


def _escape_text(value: str) -> str:
    """Escapes the three characters Vee's parser (LineParser.splitTextAndParams/
    parseParams) reads back as `\\|`/`\\n`/`\\\\`: a literal `|` would otherwise be
    read as the text/params delimiter, and a literal newline would otherwise
    split a plugin's single stdout line into two corrupted ones. Order matters:
    backslashes are escaped first, or the backslash inserted for `|`/newline
    would itself get re-escaped.
    """
    return value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", "\\n")


def _quote(value: str) -> str:
    escaped = _escape_text(value)
    # Backslash also forces quoting: an unquoted (bare) value is never
    # unescaped by the parser, so anything containing an escape must go
    # through the quoted path, which is.
    #
    # A leading quote character forces it too: the parser decides a value is
    # quoted by looking at its first character, so emitting ``"a"`` bare would
    # round-trip back as ``a`` with the quotes eaten. Values that merely
    # *contain* a quote are safe bare -- only the first position is read as a
    # delimiter.
    if _needs_quote(value) or value[:1] in ('"', "'"):
        return '"' + escaped.replace('"', '\\"') + '"'
    return escaped


def _fmt_float(x: float) -> str:
    """Formats ``x`` exactly as JavaScript's ``String(Number)`` does
    (ECMA-262 Number::toString).

    Python's own ``str`` agrees with JavaScript across the ordinary range but
    parts company at the edges -- ``1e21`` prints in full, ``1e-07`` carries a
    padded exponent -- and Go's ``'g'`` verb parts company much earlier still,
    at 1e6. Since the three SDKs commit to byte-identical output, the format
    has to be one written-down rule rather than three native defaults.
    """
    if x != x:
        return "NaN"
    if x == float("inf"):
        return "Infinity"
    if x == float("-inf"):
        return "-Infinity"
    if x == 0:
        return "0"  # also normalizes -0.0, matching String(-0)

    negative = x < 0
    s = repr(abs(x))  # shortest round-trippable digits
    if "e" in s:
        mantissa, _, exponent = s.partition("e")
        exp10 = int(exponent)
    else:
        mantissa, exp10 = s, 0
    int_part, _, frac_part = mantissa.partition(".")

    all_digits = int_part + frac_part
    stripped = all_digits.lstrip("0")
    leading_zeros = len(all_digits) - len(stripped)
    digits = stripped.rstrip("0") or "0"
    k = len(digits)
    n = len(int_part) + exp10 - leading_zeros  # position of the decimal point

    if k <= n <= 21:
        out = digits + "0" * (n - k)
    elif 0 < n <= 21:
        out = digits[:n] + "." + digits[n:]
    elif -6 < n <= 0:
        out = "0." + "0" * (-n) + digits
    else:
        e = n - 1
        sign = "+" if e >= 0 else "-"
        head = digits if k == 1 else digits[0] + "." + digits[1:]
        out = head + "e" + sign + str(abs(e))
    return "-" + out if negative else out


def _first_set(*values: Any) -> Any:
    """The first argument that is not ``None``, or ``None``.

    Used to funnel the per-accessory size options into the single
    ``accessoryw=``/``accessoryh=`` the format takes. Not ``or``-chaining:
    ``0`` is a legitimate size and must not fall through to the next option.
    """
    for value in values:
        if value is not None:
            return value
    return None


def _fmt(value: Any) -> str:
    # Match JS String(): booleans lowercase, numbers formatted by the shared
    # ECMA-262 rule so `size=12` is not `size=12.0` and a 1e6 sparkline point
    # is not `1e+06`.
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, float):
        return _fmt_float(value)
    if isinstance(value, int):
        # Python ints are unbounded; JS would render one past 2**53 as a
        # double. Route the ones that reach exponent form through the float
        # rule so the two agree.
        return str(value) if abs(value) < 10**21 else _fmt_float(float(value))
    return str(value)


# Every option `item()`/`title()` accepts, and the camelCase spellings kept
# working from before the SDK moved to snake_case.
#
# Two problems this solves at once. Unknown keyword arguments used to be
# dropped in silence -- `colour="red"` or a mistyped `sfimg=` emitted nothing,
# with no error -- where the TypeScript SDK rejects them at compile time and
# the Go SDK rejects them as unknown struct fields. And the SDK's own spelling
# was inconsistent: menu options were camelCase while layout-node options were
# snake_case, so the spelling a Python author would naturally reach for was
# exactly the one that failed silently.
_OPTION_NAMES = frozenset(
    [name for name, _ in _SCALAR_KEYS]
    + [name for name, _ in _TRAILING_KEYS]
    + [
        "shell", "params", "sf_color",
        "sparkline", "sparkline_w", "sparkline_h", "sparkline_color",
        "accessory_w", "accessory_h",
        "toggle", "slider",
        "progress", "progress_track_color", "progress_w", "progress_h",
        "chart",
    ]
)

# Deprecated camelCase spelling -> current snake_case name. Accepted with a
# DeprecationWarning so existing plugins keep running; scheduled for removal in
# the next major version.
_DEPRECATED_ALIASES = {
    "templateImage": "template_image",
    "sfColor": "sf_color",
    "sfSize": "sf_size",
    "sfConfig": "sf_config",
    "webviewW": "webview_w",
    "webviewH": "webview_h",
    "trackColor": "progress_track_color",
    "progressW": "progress_w",
    "progressH": "progress_h",
}


def _normalize_options(options: dict[str, Any]) -> dict[str, Any]:
    """Maps deprecated spellings onto current ones and rejects unknown keys."""
    out: dict[str, Any] = {}
    for name, value in options.items():
        current = _DEPRECATED_ALIASES.get(name)
        if current is not None:
            warnings.warn(
                f"{name!r} is the pre-snake_case spelling; use {current!r}. "
                "The old name still works and will be removed in the next "
                "major version.",
                DeprecationWarning,
                stacklevel=3,
            )
            name = current
        elif name not in _OPTION_NAMES:
            close = sorted(n for n in _OPTION_NAMES if n.replace("_", "") == name.lower().replace("_", ""))
            hint = f" Did you mean {close[0]!r}?" if close else ""
            raise TypeError(f"unknown option {name!r}.{hint}")
        out[name] = value
    return out


def _warn_tuple_form(option: str, mapping: str) -> None:
    """Warns about a tuple/list shorthand that only this SDK accepts.

    The three SDKs promise the same builder shape in any language, and these
    shorthands break that: TypeScript takes only the object form and Go only
    the struct, so a plugin written with a tuple does not port. The mapping
    form works identically in all three.
    """
    warnings.warn(
        f"the tuple form of {option}= is a Python-only shorthand the other SDKs "
        f"cannot express; pass {mapping} instead. It still works and will be "
        "removed in the next major version.",
        DeprecationWarning,
        stacklevel=4,
    )


def _encode(options: dict[str, Any] | None) -> str:
    if not options:
        return ""
    parts: list[str] = []

    def push(key: str, value: Any) -> None:
        if value is not None:
            parts.append(f"{key}={_quote(_fmt(value))}")

    for name, key in _SCALAR_KEYS:
        push(key, options.get(name))

    if options.get("shell") is not None:
        push("shell", options.get("shell"))
        for i, param in enumerate(options.get("params") or []):
            push(f"param{i + 1}", param)

    for name, key in _TRAILING_KEYS:
        if key == "sfsize":
            # `sfcolor` sits between `sfimage` and `sfsize` in the order the
            # three SDKs share. It accepts one colour or a list of them (one
            # per layer of a multicolour symbol), so it needs its own branch.
            sf_color = options.get("sf_color")
            if sf_color is not None:
                push("sfcolor", ",".join(str(c) for c in sf_color)
                     if isinstance(sf_color, (list, tuple)) else sf_color)
        push(key, options.get(name))

    # Vee-native rich params, emitted last in a fixed order shared across SDKs:
    # sparkline, toggle, slider, progress, trackcolor, then the chart shape with
    # its labels/colors, and finally the accessory size. The three SDKs are
    # compared byte-for-byte against ``plugins/fixtures/``, so this order is a
    # contract, not a preference.
    sparkline = options.get("sparkline")
    if sparkline is not None:
        push("sparkline", ",".join(_fmt(v) for v in sparkline))
    push("sparklinecolor", options.get("sparkline_color"))

    toggle = options.get("toggle")
    if toggle is not None:
        push("toggle", "on" if toggle else "off")

    slider = options.get("slider")
    if slider is not None:
        if isinstance(slider, dict):
            smin, smax, sval = slider["min"], slider["max"], slider["value"]
        else:  # tuple/list of (min, max, value)
            _warn_tuple_form("slider", '{"min": 0, "max": 100, "value": 40}')
            smin, smax, sval = slider
        push("slider", f"{_fmt(smin)},{_fmt(smax)},{_fmt(sval)}")

    progress = options.get("progress")
    if progress is not None:
        # A fraction goes out as-is; a value/max pair goes out as the format's
        # own two-argument form (`progress=72,100`), which Vee divides on
        # parse. That keeps the author's numbers on the wire rather than a
        # pre-divided float.
        if isinstance(progress, (tuple, list)):  # (value, max)
            _warn_tuple_form("progress", '{"value": 72, "max": 100}')
            value, maximum = progress
            push("progress", f"{_fmt(value)},{_fmt(maximum)}")
        elif isinstance(progress, dict):
            push("progress", f"{_fmt(progress['value'])},{_fmt(progress['max'])}")
        else:
            push("progress", _fmt(progress))

    push("progresstrackcolor", options.get("progress_track_color"))

    # Categorical share chart: `pie=`/`donut=`/`stackedbar=` plus its positional
    # `chartlabels=`/`chartcolors=`. All three shapes take the same data, so the
    # shape is just the key the values are pushed under. Vee reads labels and
    # colors as comma-separated lists — keep commas out of segment names.
    chart = options.get("chart")
    if chart is not None:
        push(chart["kind"], ",".join(_fmt(v) for v in chart["values"]))
        labels = chart.get("labels")
        if labels is not None:
            push("chartlabels", ",".join(str(v) for v in labels))
        colors = chart.get("colors")
        if colors is not None:
            push("chartcolors", ",".join(str(v) for v in colors))

    # One wire parameter sizes whichever accessory the row carries, so every
    # per-accessory option funnels here. They stay separate in the API because a
    # builder already knows which accessory you are describing -- the ambiguity
    # ``accessoryw=`` solves for hand-written lines cannot arise. ``"full"`` is
    # the one non-numeric width: stretch to the row's own width (stacked bars
    # and gauges only -- a circle has no free width).
    _chart = options.get("chart") or {}
    _w = _first_set(options.get("accessory_w"), options.get("sparkline_w"),
                    options.get("progress_w"), _chart.get("w"))
    _h = _first_set(options.get("accessory_h"), options.get("sparkline_h"),
                    options.get("progress_h"), _chart.get("h"))
    if _w is not None:
        push("accessoryw", _w if isinstance(_w, str) else _fmt(_w))
    if _h is not None:
        push("accessoryh", _h if isinstance(_h, str) else _fmt(_h))

    return " | " + " ".join(parts) if parts else ""


class Section:
    """A menu section at a given submenu depth (0 = top level)."""

    def __init__(self, lines: list[str], depth: int) -> None:
        self._lines = lines
        self._depth = depth

    def _prefix(self) -> str:
        return "-" * (self._depth * 2)

    def item(self, text: str, **options: Any) -> "Section":
        self._lines.append(self._prefix() + _escape_text(text) + _encode(_normalize_options(options)))
        return self

    def separator(self) -> "Section":
        self._lines.append(self._prefix() + "---")
        return self

    def submenu(self, text: str, **options: Any) -> "Section":
        """Add an item and return a ``Section`` for its submenu."""
        self.item(text, **options)
        return Section(self._lines, self._depth + 1)


class Menu:
    """The top-level menu: title line(s) plus a dropdown."""

    def __init__(self) -> None:
        self._titles: list[str] = []
        self._body: list[str] = []

    def title(self, text: str, **options: Any) -> "Menu":
        self._titles.append(_escape_text(text) + _encode(_normalize_options(options)))
        return self

    @property
    def dropdown(self) -> Section:
        return Section(self._body, 0)

    def to_string(self) -> str:
        head = "\n".join(self._titles)
        if self._body:
            return f"{head}\n---\n" + "\n".join(self._body)
        return head

    def __str__(self) -> str:  # so `str(menu)` works like TS `toString()`
        return self.to_string()

    def print(self) -> None:
        sys.stdout.write(self.to_string() + "\n")


# -----------------------------------------------------------------------------
# Widget surface contract — the rich JSON payload a plugin prints to stdout
# when invoked with VEE_TARGET=widget, instead of the xbar/SwiftBar text
# protocol above. See docs/design/widget-surface-contract.md §4. Mirrors the
# TypeScript SDK's WidgetCard field-for-field (same option names, same JSON
# key order).

# Option name -> emitted JSON key, in the exact order the TypeScript SDK
# emits them.
_CARD_KEYS: list[tuple[str, str]] = [
    ("template", "template"),
    ("title", "title"),
    ("symbol", "symbol"),
    ("tint", "tint"),
    ("value", "value"),
    ("caption", "caption"),
    ("detail", "detail"),
    ("status", "status"),
    ("progress", "progress"),
    ("trend", "trend"),
    ("items", "items"),
    ("actions", "actions"),
    ("refreshAfter", "refresh_after"),
    ("staleAfter", "stale_after"),
    ("layout", "layout"),
]


def _json_value(value: Any) -> str:
    """Serializes ``value`` to compact JSON, formatting a whole-number float
    without a trailing ``.0`` (matching ``_fmt`` / the TS and Go SDKs) —
    Python's own ``json`` module keeps ``15.0``, which would break the
    cross-language byte-identical fixture convention this SDK maintains.
    """
    if value is None:
        return "null"
    if isinstance(value, (bool, int, float)):
        return _fmt(value)
    if isinstance(value, str):
        # ensure_ascii=False matches JSON.stringify, which emits non-ASCII
        # literally. Python's default would send "✓" as "\u2713" and break the
        # byte-identical fixture convention.
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, (list, tuple)):
        return "[" + ",".join(_json_value(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{" + ",".join(
            f"{json.dumps(str(k), ensure_ascii=False)}:{_json_value(v)}"
            for k, v in value.items()
        ) + "}"
    raise TypeError(f"unsupported widget card value: {value!r}")


class WidgetCard:
    """The ``VEE_TARGET=widget`` stdout payload (see the design doc §4).
    Build one with the richest data available and call
    ``str()``/``print()`` exactly once per run; each native template
    (small/medium/large) takes what fits.

    ``items``/``actions`` are plain dicts, e.g.
    ``{"label": "Orders", "value": "214", "symbol": "bag", "tint": "blue"}``
    — field order in the dict literal is preserved in the JSON output.
    """

    def __init__(self, **options: Any) -> None:
        self._options = options

    def to_string(self) -> str:
        payload: dict[str, Any] = {"vee_widget": 1}
        for name, key in _CARD_KEYS:
            value = self._options.get(name)
            if value is not None:
                payload[key] = value
        return _json_value(payload)

    def __str__(self) -> str:  # so `str(card)` works like TS `toString()`
        return self.to_string()

    def print(self) -> None:
        sys.stdout.write(self.to_string() + "\n")


def widget_card(**options: Any) -> WidgetCard:
    """Builds a widget card. Equivalent to ``WidgetCard(**options)``."""
    return WidgetCard(**options)


def Stat(**options: Any) -> WidgetCard:
    """Glyph, big value in tint, title/caption. The default template."""
    return WidgetCard(template="stat", **options)


def Gauge(**options: Any) -> WidgetCard:
    """Stat + a native gauge from ``progress``."""
    return WidgetCard(template="gauge", **options)


def Trend(**options: Any) -> WidgetCard:
    """Stat + a sparkline from ``trend``."""
    return WidgetCard(template="trend", **options)


def List(**options: Any) -> WidgetCard:
    """``title`` header + ``items`` as rows."""
    return WidgetCard(template="list", **options)


def Board(**options: Any) -> WidgetCard:
    """A compact grid of ``items`` as stat cells (KPI board)."""
    return WidgetCard(template="board", **options)


# ── Layout tree ──────────────────────────────────────────────────────────────
# The composable escape hatch alongside the five preset templates. Nodes are
# built as ordered dicts (``_json_value`` preserves insertion order), so keys
# land in the canonical order the three SDKs share and output is byte-identical.
# Style keys are snake_case (Python idiom); the wire format is snake_case too.

_STYLE_KEYS = ["font", "tint", "align", "padding", "line_limit", "monospaced_digit", "min_scale", "fill"]
_FONT_KEYS = ["size", "point_size", "weight", "design"]


def _font(f: dict[str, Any]) -> dict[str, Any]:
    return {k: f[k] for k in _FONT_KEYS if f.get(k) is not None}


def _style(s: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for k in _STYLE_KEYS:
        v = s.get(k)
        if v is not None:
            out[k] = _font(v) if k == "font" else v
    return out


# Which options each node type accepts. `Columns` on a text node or `min_length`
# on a gauge is a mistake, not a no-op: the TypeScript SDK's option types reject
# those at compile time and the Go SDK's typed option kinds reject them too, so
# Python rejects them here rather than shipping a key the renderer ignores.
_COMMON_NODE_OPTS = frozenset({"families", "style"})
_NODE_OPTS = {
    "vstack": _COMMON_NODE_OPTS | {"align", "spacing"},
    "hstack": _COMMON_NODE_OPTS | {"align", "spacing"},
    "zstack": _COMMON_NODE_OPTS | {"align", "spacing"},
    "grid": _COMMON_NODE_OPTS | {"align", "spacing", "columns"},
    "text": _COMMON_NODE_OPTS,
    "image": _COMMON_NODE_OPTS,
    "sparkline": _COMMON_NODE_OPTS,
    "gauge": _COMMON_NODE_OPTS | {"gauge_style"},
    "spacer": {"families", "min_length"},
    "divider": {"families"},
}


def _check_node_opts(node_type: str, opts: dict[str, Any]) -> None:
    allowed = _NODE_OPTS[node_type]
    for name, value in opts.items():
        if value is None:
            continue
        if name not in allowed:
            raise TypeError(
                f"{name!r} is not a valid option for a {node_type!r} node; "
                f"it accepts {', '.join(sorted(allowed))}"
            )


def _node(
    type: str,
    *,
    text: str | None = None,
    symbol: str | None = None,
    value: float | None = None,
    values: list[float] | None = None,
    gauge_style: str | None = None,
    align: str | None = None,
    spacing: float | None = None,
    columns: int | None = None,
    min_length: float | None = None,
    families: list[str] | None = None,
    style: dict[str, Any] | None = None,
    children: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Builds a node dict with keys inserted in the shared canonical order."""
    # `text`/`symbol`/`value`/`values`/`children` are positional payload set by
    # the builders themselves, not caller-supplied options, so only the option
    # arguments are checked.
    _check_node_opts(type, {
        "gauge_style": gauge_style, "align": align, "spacing": spacing,
        "columns": columns, "min_length": min_length, "families": families,
        "style": style,
    })
    node: dict[str, Any] = {"type": type}
    if text is not None:
        node["text"] = text
    if symbol is not None:
        node["symbol"] = symbol
    if value is not None:
        node["value"] = value
    if values is not None:
        node["values"] = values
    if gauge_style is not None:
        node["gauge_style"] = gauge_style
    if align is not None:
        node["align"] = align
    if spacing is not None:
        node["spacing"] = spacing
    if columns is not None:
        node["columns"] = columns
    if min_length is not None:
        node["min_length"] = min_length
    if families is not None:
        node["families"] = families
    if style is not None:
        node["style"] = _style(style)
    if children is not None:
        node["children"] = children
    return node


class Node:
    """Builders for the layout tree, namespaced (``Node.VStack(...)``) so they
    don't collide with the card-level template builders (``Stat``/``Gauge``/…).
    Each returns a plain dict; pass the root as ``widget_card(layout=...)``.
    """

    @staticmethod
    def VStack(children: list[dict[str, Any]], **opts: Any) -> dict[str, Any]:
        """A vertical stack."""
        return _node("vstack", children=children, **opts)

    @staticmethod
    def HStack(children: list[dict[str, Any]], **opts: Any) -> dict[str, Any]:
        """A horizontal stack — side-by-side regions."""
        return _node("hstack", children=children, **opts)

    @staticmethod
    def ZStack(children: list[dict[str, Any]], **opts: Any) -> dict[str, Any]:
        """A depth stack — overlays and rings."""
        return _node("zstack", children=children, **opts)

    @staticmethod
    def Grid(children: list[dict[str, Any]], **opts: Any) -> dict[str, Any]:
        """A grid of ``columns`` (default 2, clamped 1…4)."""
        return _node("grid", children=children, **opts)

    @staticmethod
    def Text(text: str, **opts: Any) -> dict[str, Any]:
        """A text run."""
        return _node("text", text=text, **opts)

    @staticmethod
    def Image(symbol: str, **opts: Any) -> dict[str, Any]:
        """An SF Symbol glyph (v1 renders SF Symbols only)."""
        return _node("image", symbol=symbol, **opts)

    @staticmethod
    def Gauge(value: float, **opts: Any) -> dict[str, Any]:
        """A gauge — ``linear`` (default) or ``circular``. ``value`` is 0…1."""
        return _node("gauge", value=value, **opts)

    @staticmethod
    def Sparkline(values: list[float], **opts: Any) -> dict[str, Any]:
        """A dependency-free line chart from ``values``."""
        return _node("sparkline", values=values, **opts)

    @staticmethod
    def Spacer(**opts: Any) -> dict[str, Any]:
        """Flexible empty space."""
        return _node("spacer", **opts)

    @staticmethod
    def Divider(**opts: Any) -> dict[str, Any]:
        """A hairline divider."""
        return _node("divider", **opts)


# -----------------------------------------------------------------------------
# Structured-JSON output — the optional alternative to the text protocol above.
# A plugin opts in by printing a single ``{"vee":1,…}`` object; Vee decodes it
# directly, with no line parsing, no ``|``-separated parameters and no quoting
# rules. See docs/_content/json-output.md.
#
# ``JSONMenu`` deliberately mirrors ``Menu`` method for method -- ``title``,
# ``dropdown``, ``item``, ``separator``, ``submenu``, ``to_string``, ``print``
# -- so choosing a wire format does not mean learning a second builder.

# The key order every SDK emits, so the three produce byte-identical JSON.
_JSON_ITEM_KEYS = [
    "text", "separator", "color", "size", "href", "shell", "params", "terminal",
    "refresh", "sfimage", "disabled", "checked", "tooltip", "header", "accessory",
    "sparkline", "sparkline_width", "sparkline_height", "sparkline_color",
    "accessory_width", "accessory_height",
    "toggle", "slider", "progress", "progress_track_color", "progress_width",
    "progress_height", "chart", "submenu", "alternate",
]

# snake_case option -> the JSON key it emits. The wire format is camelCase; the
# SDK keeps Python's spelling, matching how the text-protocol options work.
_JSON_KEY_NAMES = {
    "accessory_width": "accessoryWidth",
    "accessory_height": "accessoryHeight",
    "sparkline_width": "sparklineWidth",
    "sparkline_height": "sparklineHeight",
    "sparkline_color": "sparklineColor",
    "progress_track_color": "progressTrackColor",
    "progress_width": "progressWidth",
    "progress_height": "progressHeight",
}

# The JSON protocol carries a subset of the text protocol's parameters, so an
# option it cannot express is rejected rather than silently dropped -- matching
# the TypeScript SDK, where it is a compile error.
_JSON_OPTION_NAMES = frozenset(_JSON_ITEM_KEYS) - {"text", "separator", "submenu"}


def _order_json_item(item: dict[str, Any]) -> dict[str, Any]:
    """Rebuilds an item with keys in the shared canonical order, dropping absent
    ones and recursing into ``submenu``/``alternate``."""
    out: dict[str, Any] = {}
    for key in _JSON_ITEM_KEYS:
        value = item.get(key)
        if value is None:
            continue
        wire = _JSON_KEY_NAMES.get(key, key)
        if key == "submenu":
            out[wire] = [_order_json_item(child) for child in value]
        elif key == "alternate":
            out[wire] = _order_json_item(value)
        else:
            out[wire] = value
    return out


def _check_json_options(options: dict[str, Any]) -> dict[str, Any]:
    for name in options:
        if name not in _JSON_OPTION_NAMES:
            hint = ""
            if name in _OPTION_NAMES:
                hint = (" It is a text-protocol option; the JSON format carries "
                        "a subset of them.")
            raise TypeError(f"unknown JSON menu option {name!r}.{hint}")
    return options


class JSONSection:
    """A JSON menu section at a given submenu depth. Mirrors ``Section``."""

    def __init__(self, items: list[dict[str, Any]]) -> None:
        self._items = items

    def item(self, text: str, **options: Any) -> "JSONSection":
        self._items.append({"text": text, **_check_json_options(options)})
        return self

    def separator(self) -> "JSONSection":
        self._items.append({"separator": True})
        return self

    def submenu(self, text: str, **options: Any) -> "JSONSection":
        """Add an item and return a ``JSONSection`` for its submenu."""
        submenu: list[dict[str, Any]] = []
        self._items.append({"text": text, **_check_json_options(options), "submenu": submenu})
        return JSONSection(submenu)


class JSONMenu:
    """The top-level JSON menu: title line(s) plus a dropdown. Mirrors ``Menu``."""

    def __init__(self) -> None:
        self._titles: list[dict[str, Any]] = []
        self._body: list[dict[str, Any]] = []

    def title(self, text: str, **options: Any) -> "JSONMenu":
        self._titles.append({"text": text, **_check_json_options(options)})
        return self

    @property
    def dropdown(self) -> JSONSection:
        return JSONSection(self._body)

    def to_string(self) -> str:
        payload: dict[str, Any] = {
            "vee": 1,
            "title": [_order_json_item(t) for t in self._titles],
        }
        if self._body:
            payload["items"] = [_order_json_item(i) for i in self._body]
        return _json_value(payload)

    def __str__(self) -> str:
        return self.to_string()

    def print(self) -> None:
        sys.stdout.write(self.to_string() + "\n")
"""#

}
