import Foundation
import VeeProtocol
import VeeFuzzy

// MARK: - Seam: pasteboard reading

/// An immutable VALUE snapshot of one pasteboard item — the only thing that
/// crosses the OS seam. The privacy filter and the capture pipeline are pure
/// logic over this struct, so they are fully unit-testable without `NSPasteboard`.
///
/// `types` are the declared UTIs / custom pasteboard type identifiers present on
/// the item (e.g. `public.utf8-plain-text`, `org.nspasteboard.ConcealedType`,
/// `com.agilebits.onepassword`). `text` is the plain-text representation if one
/// is present (nil for non-text items, which the monitor ignores).
public struct PasteboardItemSnapshot: Hashable, Sendable {
    public var types: [String]
    public var text: String?
    public init(types: [String], text: String?) {
        self.types = types
        self.text = text
    }
}

/// The OS seam over `NSPasteboard`. The fake (tests) and the thin real adapter
/// both conform; NO business logic lives below this line. `changeCount` mirrors
/// `NSPasteboard.changeCount` (monotonic, bumped on every write); the monitor
/// polls it and reads a snapshot only when it increments.
public protocol PasteboardReading: AnyObject {
    var changeCount: Int { get }
    func currentSnapshot() -> PasteboardItemSnapshot
}

// MARK: - The privacy filter (PURE — security-critical path)

/// A pure predicate over a `PasteboardItemSnapshot` deciding whether an item is
/// privacy-sensitive and must be DROPPED (never recorded to history or disk).
///
/// This is the security heart of the clipboard provider. It has zero OS
/// dependencies and zero state beyond its blocklists, so cases 3/4/5 can assert
/// the contract directly. Matching is exact on the item's declared types.
public struct ClipboardPrivacyFilter: Sendable {
    /// NSPasteboard.org privacy conventions — content explicitly marked as not
    /// for recording. These are non-negotiable and always present.
    public static let concealedConventionTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Default password-manager / clipping proprietary UTIs that ship blocked
    /// (mirrors Maccy's default ignored set). User-editable via the monitor.
    public static let defaultPasswordManagerBlocklist: Set<String> = [
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]

    /// The convention types (always enforced) plus the configured UTI blocklist.
    public var blocklist: Set<String>

    public init(blocklist: Set<String>) {
        self.blocklist = blocklist
    }

    /// The default filter: NSPasteboard.org conventions + password-manager UTIs.
    public static let `default` = ClipboardPrivacyFilter(
        blocklist: concealedConventionTypes.union(defaultPasswordManagerBlocklist)
    )

    /// True when the snapshot carries ANY privacy-sensitive type and must be
    /// dropped before it can enter history or persistence.
    public func shouldDrop(_ snapshot: PasteboardItemSnapshot) -> Bool {
        for type in snapshot.types where blocklist.contains(type) {
            return true
        }
        return false
    }
}

// MARK: - In-memory history entry (pin state lives above the wire type)

/// Internal history record. The wire `ClipboardItem` (id, text, copiedAt) is
/// derived from this; `pinned` is host-side state the contract type doesn't carry.
struct ClipboardEntry {
    var item: ClipboardItem
    var pinned: Bool
}

// MARK: - The monitor

/// Polls an injectable `PasteboardReading.changeCount` over an injectable
/// `Clock`; on increment reads a snapshot, applies the PURE privacy filter, and
/// (if it survives) records a `ClipboardItem` into the in-memory history.
///
/// Everything here is above the OS seam and is fully tested with fakes. The
/// monitor holds NO `NSPasteboard` reference — only a `PasteboardReading`.
public final class ClipboardMonitor {
    private let pasteboard: PasteboardReading
    private let clock: Clock
    private let historyLimit: Int

    /// Privacy filter — convention types are always enforced; the UTI blocklist
    /// is user-editable via `addToBlocklist`.
    public private(set) var filter: ClipboardPrivacyFilter

    /// Newest-first in-memory history. Dropped content never enters this array.
    private var entries: [ClipboardEntry] = []
    /// Last observed change count; capture fires only when the live count exceeds it.
    private var lastChangeCount: Int
    /// One-shot "ignore next copy" latch.
    private var ignoreNext = false
    private var counter = 0

    /// - Parameters:
    ///   - pasteboard: the OS seam.
    ///   - clock: time source for `copiedAt` timestamps.
    ///   - historyLimit: max retained NON-pinned items (default 200). Pinned
    ///     items always survive trimming.
    ///   - filter: privacy filter (default: conventions + password-manager UTIs).
    public init(pasteboard: PasteboardReading,
                clock: Clock,
                historyLimit: Int = 200,
                filter: ClipboardPrivacyFilter = .default) {
        self.pasteboard = pasteboard
        self.clock = clock
        self.historyLimit = max(1, historyLimit)
        self.filter = filter
        // Seed from the current count so we don't capture whatever predates us.
        self.lastChangeCount = pasteboard.changeCount
    }

    /// The polling default Maccy uses; the real timer adapter ticks at this rate.
    public static let defaultPollInterval: TimeInterval = 0.5

    // MARK: Configuration

    /// Add a UTI to the user-editable blocklist (convention types stay enforced).
    public func addToBlocklist(_ type: String) {
        filter.blocklist.insert(type)
    }

    /// Remove a user-added UTI from the blocklist. Callers should not remove the
    /// `ClipboardPrivacyFilter.concealedConventionTypes` — the default filter
    /// includes them and they are the privacy guarantee.
    public func removeFromBlocklist(_ type: String) {
        filter.blocklist.remove(type)
    }

    /// Drop exactly the next captured copy, then resume normally (one-shot).
    public func ignoreNextCopy() {
        ignoreNext = true
    }

    // MARK: Capture

    /// One poll tick. Reads `changeCount`; on an increment, snapshots the
    /// pasteboard and routes it through the privacy filter + ignore latch.
    /// Idempotent when nothing changed.
    public func poll() {
        let live = pasteboard.changeCount
        guard live > lastChangeCount else { return }
        lastChangeCount = live

        let snapshot = pasteboard.currentSnapshot()
        capture(snapshot)
    }

    /// PURE capture pipeline over a snapshot (no OS access) — exposed for tests
    /// and reuse. Drops privacy-flagged or "ignore next" items BEFORE they can
    /// reach history; only text-bearing, non-empty items are recorded.
    func capture(_ snapshot: PasteboardItemSnapshot) {
        // Security: privacy-flagged content is dropped before anything else.
        if filter.shouldDrop(snapshot) { return }

        // One-shot ignore consumes the latch regardless of content.
        if ignoreNext {
            ignoreNext = false
            return
        }

        guard let text = snapshot.text, !text.isEmpty else { return }

        let item = ClipboardItem(id: nextID(), text: text, copiedAt: clock.now)
        entries.insert(ClipboardEntry(item: item, pinned: false), at: 0)
        trim()
    }

    private func nextID() -> String {
        counter += 1
        return "clip-\(counter)"
    }

    /// Trim oldest NON-pinned entries beyond the cap; pinned entries always survive.
    private func trim() {
        var nonPinnedKept = 0
        var result: [ClipboardEntry] = []
        result.reserveCapacity(entries.count)
        // entries is newest-first; keep the newest `historyLimit` non-pinned plus
        // all pinned.
        for entry in entries {
            if entry.pinned {
                result.append(entry)
            } else if nonPinnedKept < historyLimit {
                result.append(entry)
                nonPinnedKept += 1
            }
            // else: an old non-pinned entry beyond the cap → dropped.
        }
        entries = result
    }

    // MARK: Pinning

    /// Pin an item by id so it survives history trimming.
    public func pin(id: String) { setPinned(id: id, pinned: true) }
    /// Unpin an item by id.
    public func unpin(id: String) { setPinned(id: id, pinned: false) }

    private func setPinned(id: String, pinned: Bool) {
        guard let idx = entries.firstIndex(where: { $0.item.id == id }) else { return }
        entries[idx].pinned = pinned
    }

    // MARK: Query

    /// Full newest-first history (wire items only).
    public func history() -> [ClipboardItem] {
        entries.map(\.item)
    }

    /// Search the in-memory history. Empty query → newest-first, capped at
    /// `limit`. Non-empty query → fuzzy-filtered + ranked via `VeeFuzzy` over
    /// each item's text, capped at `limit`.
    public func history(query: String, limit: Int) -> [ClipboardItem] {
        let cap = max(0, limit)
        if query.isEmpty {
            return Array(entries.prefix(cap).map(\.item))
        }
        // Map each entry's text into a Candidate (id == item id) and let the
        // native matcher score; non-matches are excluded by FuzzyMatcher.
        let candidates = entries.map { entry in
            Candidate(id: entry.item.id, title: entry.item.text)
        }
        let scored = FuzzyMatcher.match(query: query, in: candidates)
        let byID = Dictionary(entries.map { ($0.item.id, $0.item) }, uniquingKeysWith: { a, _ in a })
        var out: [ClipboardItem] = []
        out.reserveCapacity(min(cap, scored.count))
        for s in scored.prefix(cap) {
            if let item = byID[s.candidate.id] { out.append(item) }
        }
        return out
    }
}
