import Foundation
import VeeProtocol
import VeeFuzzy
import VeeKeychain
import VeeCache

/// Host-native providers that need long-lived OS resources and must outlive any
/// single plugin: clipboard monitor, app search, calendar reader, hotkey registry.
///
/// Every OS touch point sits behind a protocol seam with a fake (tests) and a
/// thin, logic-free real adapter:
///   - `PasteboardReading`  → `ClipboardMonitor` (+ pure `ClipboardPrivacyFilter`)
///   - `AppEnumerating`     → `AppSearchProvider` (fuzzy + frecency)
///   - `CalendarProvider`   → `CalendarService` (+ pure `MeetingLinkDetector`;
///                            thin `EventKitCalendarProvider` under `#if canImport(EventKit)`)
///   - `HotkeyRegistry`     → `HotkeyDispatcher` (conflict detection;
///                            thin `CarbonHotkeyRegistry` under `#if canImport(Carbon)`)
///   - `Clock`              → injected time for timestamps / frecency decay
///
/// The clipboard privacy filter (drop `ConcealedType`/`TransientType`/
/// `AutoGeneratedType` + the password-manager UTI blocklist) is PURE logic over
/// the `PasteboardItemSnapshot` value type — the security-critical path — and is
/// fully unit-tested. No business logic lives below a seam.
public enum HostServices {}
