import Foundation
import VeeProtocol
import VeeFuzzy
import VeeKeychain
import VeeCache

/// Host-native providers that need long-lived OS resources and must outlive any
/// single plugin: clipboard monitor, app search, calendar reader, hotkey registry.
///
/// > Wave 2b worker: implement per build plan §4. Put every OS touch point behind
/// > a protocol seam (`PasteboardReading`, `AppEnumerating`, `CalendarProvider`,
/// > `HotkeyRegistry`) with a fake for tests and a thin real adapter. The
/// > clipboard privacy filter (drop `ConcealedType`/`TransientType`/
/// > `AutoGeneratedType` + password-manager UTIs) is PURE logic over a snapshot
/// > value type and MUST be fully tested — it is the security-critical path.
/// > Tests first.
public enum HostServices {
    // Wave 0 stub namespace: real provider types land in Wave 2b.
}
