#!/usr/bin/env python3
"""Render docs/api/params.json into the Markdown partials the guides include.

The plugin format's parameter surface is authored once, as data, in
``docs/api/params.json``. Every published table describing it is produced from
that file by this script and written to ``docs/_content/_generated/``; the pages
pull them in with an ``<!-- include: _generated/<name>.md -->`` directive that
the Astro build expands (see ``docs-site/src/remark-include.mjs``).

    python3 docs/scripts/build_reference.py            # write the partials
    python3 docs/scripts/build_reference.py --check    # exit 1 if any is stale

This exists because the chart surface could not be answered from the docs at
all: the kinds were spread across a forty-row parameter table, two prose
sections, a separate widgets page, and three SDKs, and nothing listed them. A
cross-product that wide goes stale the moment it is typed by hand — which is why
it is generated here, and why ``check_params.py`` verifies the numbers in it
against the Swift that defines them.

Pure standard library: the guard scripts stay dependency-free even though
the site build no longer is.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DOCS = os.path.dirname(HERE)
ROOT = os.path.dirname(DOCS)
SPEC = os.path.join(DOCS, "api", "params.json")
OUT = os.path.join(DOCS, "_content", "_generated")

BANNER = ("<!-- Generated by docs/scripts/build_reference.py from "
          "docs/api/params.json. Do not edit; edit the JSON and re-run. -->")


def load():
    with open(SPEC, encoding="utf-8") as handle:
        return json.load(handle)


def cell(text):
    """Escape a table cell: a literal pipe would end the column early."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def key_label(param):
    """How a parameter is written in the first column.

    ``displayKey`` exists for the two keys whose documented spelling is not the
    lowercase one the parser dispatches on: the open-ended ``param0, param1, …``
    family, and ``templateImage``.
    """
    names = [param.get("displayKey", param["key"])] + list(param.get("aliases", []))
    return " / ".join("`%s`" % n for n in names)


def params_table(spec):
    out = [BANNER, ""]
    by_group = {}
    for param in spec["parameters"]:
        by_group.setdefault(param["group"], []).append(param)

    for group in spec["groups"]:
        rows = by_group.get(group["id"])
        if not rows:
            continue
        out += ["### %s" % group["title"], "", group["blurb"], "",
                "| Parameter | Type | Default | Applies to | Description |",
                "| --------- | ---- | ------- | ---------- | ----------- |"]
        for param in rows:
            summary = param["summary"]
            if param.get("deprecated"):
                summary = "**Deprecated** — use `%s=` instead. %s" % (
                    param["replacedBy"], summary)
            if param.get("note"):
                summary = "%s %s" % (summary, param["note"])
            if param.get("section"):
                summary += " [More](#%s)" % param["section"]
            out.append("| %s | %s | %s | %s | %s |" % (
                key_label(param),
                cell(param.get("grammar") or param["type"]),
                cell(param.get("default", "—")),
                cell(param.get("appliesTo", "any line")),
                cell(summary)))
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def chart_matrix(spec):
    """Two tables: where each chart comes from, and what each one takes.

    One table would need nine columns and would not survive a phone. The split
    is by question — "how do I emit this?" and "what can I set on it?" — because
    those are asked at different moments.
    """
    charts = spec["charts"]
    out = [BANNER, "",
           "**Where each chart comes from.** The same chart is spelled "
           "differently depending on which output format a plugin uses; a dash "
           "means that surface cannot draw it.", "",
           "| Chart | Text protocol | JSON menu output | Widget card |",
           "| ----- | ------------- | ---------------- | ----------- |"]
    for chart in charts:
        surfaces = chart["surfaces"]
        out.append("| **%s** — %s | %s | %s | %s |" % (
            cell(chart["name"]), cell(chart["shape"]),
            code_or_dash(surfaces["text"]),
            code_or_dash(surfaces["json"]),
            code_or_dash(surfaces["widget"])))

    out += ["", "**What each chart takes.** Options are named for the chart "
            "they belong to, not shared across all of them — a sparkline takes "
            "`sparklinew=`, a share chart takes `chartw=`, and a progress bar "
            "takes `progressw=`.", "",
            "| Chart | Options | Default size | Full width | Limits | Click |",
            "| ----- | ------- | ------------ | ---------- | ------ | ----- |"]
    for chart in charts:
        out.append("| **%s** | %s | %s | %s | %s | %s |" % (
            cell(chart["name"]),
            ", ".join("`%s`" % k for k in chart["knobs"]),
            cell(chart["defaults"]),
            cell(chart["fullWidth"]),
            cell(chart["limits"]),
            cell(chart["popover"])))
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def code_or_dash(value):
    return "—" if value == "—" else "`%s`" % cell(value)


PARTIALS = {
    "params-table.md": params_table,
    "chart-matrix.md": chart_matrix,
}


def main():
    check = "--check" in sys.argv
    spec = load()
    if not check:
        os.makedirs(OUT, exist_ok=True)
    stale = []
    for name, builder in sorted(PARTIALS.items()):
        rendered = builder(spec)
        target = os.path.join(OUT, name)
        current = None
        if os.path.exists(target):
            with open(target, encoding="utf-8") as handle:
                current = handle.read()
        if current == rendered:
            continue
        if check:
            stale.append(name)
            continue
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(rendered)
        print("wrote _content/_generated/%s" % name)

    if stale:
        print("stale generated partials: %s" % ", ".join(stale), file=sys.stderr)
        print("run: python3 docs/scripts/build_reference.py", file=sys.stderr)
        return 1
    if check:
        print("generated partials are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
