import XCTest
@testable import VeeServices
import VeeProtocol
import VeeFuzzy

/// VeeServices TDD suite — build plan §4 (host-native providers behind OS seams).
///
/// Every OS touch point is behind a protocol seam with a fake; the business
/// logic above the seam is what these tests exercise. The clipboard privacy
/// filter (cases 3–5) is the security-critical path: concealed / transient /
/// auto-generated / blocklisted content must NEVER enter the in-memory history.
final class VeeServicesTests: XCTestCase {

    // MARK: - Fakes (seam doubles)

    /// Injectable pasteboard the test drives by hand: set a snapshot, bump the
    /// change count, let the monitor poll.
    private final class FakePasteboard: PasteboardReading {
        var snapshot: PasteboardItemSnapshot = .init(types: [], text: nil)
        private(set) var changeCount: Int = 0

        /// Simulate a user copy: install a snapshot and bump the counter (as
        /// `NSPasteboard` does on every write).
        func write(_ snap: PasteboardItemSnapshot) {
            snapshot = snap
            changeCount += 1
        }

        func currentSnapshot() -> PasteboardItemSnapshot { snapshot }
    }

    private static func textSnapshot(_ text: String,
                                     extraTypes: [String] = []) -> PasteboardItemSnapshot {
        PasteboardItemSnapshot(types: ["public.utf8-plain-text"] + extraTypes, text: text)
    }

    // MARK: - 1. changeCount increments → new item captured with its text

    func testChangeCountIncrementCapturesItem() {
        let pb = FakePasteboard()
        let clock = ManualClock()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: clock)

        pb.write(Self.textSnapshot("hello world"))
        monitor.poll()

        let history = monitor.history()
        XCTAssertEqual(history.count, 1)
        XCTAssertEqual(history.first?.text, "hello world")
    }

    // MARK: - 2. No-change poll → no new item

    func testNoChangePollDoesNothing() {
        let pb = FakePasteboard()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: ManualClock())

        pb.write(Self.textSnapshot("first"))
        monitor.poll()
        XCTAssertEqual(monitor.history().count, 1)

        // Poll again with no new copy: changeCount unchanged → no capture.
        monitor.poll()
        monitor.poll()
        XCTAssertEqual(monitor.history().count, 1)
    }

    // MARK: - 3. SECURITY: a ConcealedType item is DROPPED (headline)

    func testConcealedTypeIsDropped() {
        let pb = FakePasteboard()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: ManualClock())

        // A password manager marks the item concealed; it carries text but must
        // never be recorded.
        pb.write(Self.textSnapshot("hunter2-secret",
                                   extraTypes: ["org.nspasteboard.ConcealedType"]))
        monitor.poll()

        XCTAssertEqual(monitor.history().count, 0, "Concealed content must never enter history")
        XCTAssertFalse(monitor.history().contains { $0.text == "hunter2-secret" })

        // The pure predicate, exercised directly, is the security contract.
        let snap = Self.textSnapshot("x", extraTypes: ["org.nspasteboard.ConcealedType"])
        XCTAssertTrue(ClipboardPrivacyFilter.default.shouldDrop(snap))
    }

    // MARK: - 4. SECURITY: Transient + AutoGenerated dropped; 1Password UTI dropped

    func testTransientAutoGeneratedAndPasswordManagerUTIDropped() {
        let pb = FakePasteboard()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: ManualClock())

        pb.write(Self.textSnapshot("transient",
                                   extraTypes: ["org.nspasteboard.TransientType"]))
        monitor.poll()

        pb.write(Self.textSnapshot("autogen",
                                   extraTypes: ["org.nspasteboard.AutoGeneratedType"]))
        monitor.poll()

        pb.write(Self.textSnapshot("1pw-secret",
                                   extraTypes: ["com.agilebits.onepassword"]))
        monitor.poll()

        XCTAssertEqual(monitor.history().count, 0, "All privacy-flagged items dropped")

        // Each flavour, directly against the pure predicate.
        let f = ClipboardPrivacyFilter.default
        XCTAssertTrue(f.shouldDrop(Self.textSnapshot("a", extraTypes: ["org.nspasteboard.TransientType"])))
        XCTAssertTrue(f.shouldDrop(Self.textSnapshot("b", extraTypes: ["org.nspasteboard.AutoGeneratedType"])))
        XCTAssertTrue(f.shouldDrop(Self.textSnapshot("c", extraTypes: ["com.agilebits.onepassword"])))
        // The rest of the default password-manager blocklist.
        for uti in ["com.typeit4me.clipping",
                    "de.petermaurer.TransientPasteboardType",
                    "Pasteboard generator type",
                    "net.antelle.keeweb"] {
            XCTAssertTrue(f.shouldDrop(Self.textSnapshot("z", extraTypes: [uti])),
                          "default blocklist must drop \(uti)")
        }
        // A plain text item is NOT dropped.
        XCTAssertFalse(f.shouldDrop(Self.textSnapshot("ordinary clipboard text")))
    }

    // MARK: - 5. SECURITY: user blocklist + one-shot "ignore next copy"

    func testUserBlocklistAndIgnoreNextCopy() {
        let pb = FakePasteboard()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: ManualClock())

        // User adds a custom app's UTI to the editable blocklist.
        monitor.addToBlocklist("com.example.secretapp")
        pb.write(Self.textSnapshot("from-secret-app",
                                   extraTypes: ["com.example.secretapp"]))
        monitor.poll()
        XCTAssertEqual(monitor.history().count, 0, "User-blocklisted UTI dropped")

        // "Ignore next copy" drops exactly one, then resumes.
        monitor.ignoreNextCopy()
        pb.write(Self.textSnapshot("ignored-once"))
        monitor.poll()
        XCTAssertEqual(monitor.history().count, 0, "ignore-next-copy drops the next item")

        pb.write(Self.textSnapshot("captured-after"))
        monitor.poll()
        XCTAssertEqual(monitor.history().map(\.text), ["captured-after"],
                       "ignore-next-copy is one-shot; subsequent copies resume")
    }

    // MARK: - 6. History size cap trims oldest non-pinned; pinned survive

    func testHistoryCapTrimsOldestNonPinnedAndPinnedSurvive() {
        let pb = FakePasteboard()
        let clock = ManualClock()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: clock, historyLimit: 3)

        func copy(_ s: String) {
            pb.write(Self.textSnapshot(s))
            monitor.poll()
            clock.advance(by: 1)
        }

        copy("one")
        copy("two")
        copy("three")
        // Pin the oldest ("one") so it survives trimming.
        let oneID = monitor.history().first { $0.text == "one" }!.id
        monitor.pin(id: oneID)

        copy("four")   // cap is 3 → must trim oldest NON-pinned ("two")
        copy("five")   // trim "three"

        let texts = Set(monitor.history().map(\.text))
        XCTAssertTrue(texts.contains("one"), "pinned item must survive trimming")
        XCTAssertFalse(texts.contains("two"), "oldest non-pinned trimmed first")
        XCTAssertTrue(texts.contains("four"))
        XCTAssertTrue(texts.contains("five"))
        // Total retained = pinned("one") + at most `cap` non-pinned.
        XCTAssertLessThanOrEqual(monitor.history().count, 4)
    }

    // MARK: - 7. Clipboard search via VeeFuzzy filters the in-memory set

    func testClipboardSearchUsesFuzzyMatcher() {
        let pb = FakePasteboard()
        let monitor = ClipboardMonitor(pasteboard: pb, clock: ManualClock(), historyLimit: 50)

        for s in ["github.com/anthropics", "apple keynote notes", "ghost in the shell", "random text"] {
            pb.write(Self.textSnapshot(s))
            monitor.poll()
        }

        let results = monitor.history(query: "ghub", limit: 10)
        XCTAssertFalse(results.isEmpty)
        // "github.com/anthropics" is the strongest fuzzy hit for "ghub".
        XCTAssertEqual(results.first?.text, "github.com/anthropics")
        // A non-matching query returns nothing.
        XCTAssertTrue(monitor.history(query: "zzzzzqqq", limit: 10).isEmpty)
        // limit is honoured.
        XCTAssertLessThanOrEqual(monitor.history(query: "", limit: 2).count, 2)
    }

    // MARK: - App search seam fake

    private final class FakeAppEnumerator: AppEnumerating {
        var records: [AppRecord]
        init(_ records: [AppRecord]) { self.records = records }
        func enumerateApps() -> [AppRecord] { records }
    }

    // MARK: - 8. App search: exact prefix beats mid-word; frecency boosts

    func testAppSearchPrefixBeatsMidwordAndFrecencyBoost() {
        // "saf" is an exact prefix of "Safari" and a mid-word subsequence of
        // "Microsoft Safe Browser" — prefix must win.
        let enumr = FakeAppEnumerator([
            AppRecord(name: "Safari", bundleId: "com.apple.Safari", path: "/Applications/Safari.app"),
            AppRecord(name: "Microsoft Safe Browser", bundleId: "com.ms.safe", path: "/Applications/Safe.app"),
        ])
        let clock = ManualClock()
        let provider = AppSearchProvider(enumerator: enumr, clock: clock)

        let ranked = provider.search(query: "saf", limit: 10)
        XCTAssertEqual(ranked.first?.title, "Safari", "exact prefix must outrank mid-word subsequence")

        // Frecency: two equally-fuzzy apps; the one launched recently/often wins.
        let enumr2 = FakeAppEnumerator([
            AppRecord(name: "Notes", bundleId: "com.apple.Notes", path: "/Applications/Notes.app"),
            AppRecord(name: "Notion", bundleId: "com.notion.id", path: "/Applications/Notion.app"),
        ])
        let clock2 = ManualClock()
        let provider2 = AppSearchProvider(enumerator: enumr2, clock: clock2)

        // Launch Notion several times recently.
        for _ in 0..<5 { provider2.recordLaunch(bundleId: "com.notion.id") }
        clock2.advance(by: 60)   // a minute later, query

        let ranked2 = provider2.search(query: "no", limit: 10)
        XCTAssertEqual(ranked2.first?.title, "Notion",
                       "frecency (frequent+recent) must boost an equally-fuzzy app")

        // Recency decay: an old single launch loses to a fresh single launch.
        let enumr3 = FakeAppEnumerator([
            AppRecord(name: "Numbers", bundleId: "com.apple.Numbers", path: "/Applications/Numbers.app"),
            AppRecord(name: "Nudge", bundleId: "com.nudge.app", path: "/Applications/Nudge.app"),
        ])
        let clock3 = ManualClock()
        let provider3 = AppSearchProvider(enumerator: enumr3, clock: clock3)
        provider3.recordLaunch(bundleId: "com.apple.Numbers")
        clock3.advance(by: 60 * 60 * 24 * 90)  // 90 days (≫ 30d half-life)
        provider3.recordLaunch(bundleId: "com.nudge.app")  // fresh launch

        let ranked3 = provider3.search(query: "nu", limit: 10)
        XCTAssertEqual(ranked3.first?.title, "Nudge",
                       "a fresh launch must outrank a 90-day-old launch (recency decay)")
    }

    // MARK: - 9. App enumeration dedups same bundleId across roots

    func testAppEnumerationDedupsByBundleId() {
        let enumr = FakeAppEnumerator([
            AppRecord(name: "Safari", bundleId: "com.apple.Safari", path: "/Applications/Safari.app"),
            // Same bundleId discovered under a second root.
            AppRecord(name: "Safari", bundleId: "com.apple.Safari", path: "/System/Applications/Safari.app"),
            AppRecord(name: "Mail", bundleId: "com.apple.mail", path: "/System/Applications/Mail.app"),
        ])
        let provider = AppSearchProvider(enumerator: enumr, clock: ManualClock())

        let all = provider.search(query: "", limit: 50)
        let safariHits = all.filter { $0.title == "Safari" }
        XCTAssertEqual(safariHits.count, 1, "same bundleId across roots dedups to one candidate")
        XCTAssertEqual(all.count, 2, "Safari (deduped) + Mail")
    }

    // MARK: - Calendar seam fake (raw events the service maps + link-detects)

    private final class FakeCalendar: CalendarProvider {
        var events: [RawCalendarEvent]
        init(_ events: [RawCalendarEvent]) { self.events = events }
        func fetchRawEvents(from start: Date, to end: Date) -> [RawCalendarEvent] {
            events.filter { $0.start >= start && $0.start <= end }
        }
    }

    // MARK: - 10. Calendar: upcoming() sorted; meeting-link from NOTES

    func testCalendarUpcomingSortedAndMeetingLinkFromNotes() {
        let now = Date(timeIntervalSince1970: 2_000_000)
        let clock = ManualClock(now: now)

        // Out-of-order events; one carries a Zoom link in NOTES (location is a
        // physical room), another a Teams link in NOTES.
        let later = RawCalendarEvent(
            id: "b", title: "Later", start: now.addingTimeInterval(7200), end: now.addingTimeInterval(9000),
            location: "Room 4B", notes: "Join Zoom Meeting https://zoom.us/j/9876543210?pwd=abcDEF")
        let sooner = RawCalendarEvent(
            id: "a", title: "Sooner", start: now.addingTimeInterval(600), end: now.addingTimeInterval(2400),
            location: "Conf Room A", notes: "Dial in via Teams https://teams.microsoft.com/l/meetup-join/19%3ameeting_abc/0")
        // A past event must be excluded from upcoming().
        let past = RawCalendarEvent(
            id: "p", title: "Past", start: now.addingTimeInterval(-3600), end: now.addingTimeInterval(-1800),
            location: "", notes: "")

        let provider = CalendarService(provider: FakeCalendar([later, sooner, past]), clock: clock)
        let upcoming = provider.upcoming(within: 60 * 60 * 24)

        XCTAssertEqual(upcoming.map(\.id), ["a", "b"], "sorted by start, past excluded")
        XCTAssertEqual(upcoming[0].meetingURL, "https://teams.microsoft.com/l/meetup-join/19%3ameeting_abc/0",
                       "Teams link extracted from NOTES when location is a room")
        XCTAssertEqual(upcoming[1].meetingURL, "https://zoom.us/j/9876543210?pwd=abcDEF",
                       "Zoom link extracted from NOTES")

        // Direct exercise of the pure regex detector across services.
        XCTAssertEqual(MeetingLinkDetector.detect(location: "Room", notes: "zoommtg://zoom.us/join?confno=123"),
                       "zoommtg://zoom.us/join?confno=123")
        XCTAssertEqual(MeetingLinkDetector.detect(location: "https://meet.google.com/abc-defg-hij", notes: ""),
                       "https://meet.google.com/abc-defg-hij")
        XCTAssertNotNil(MeetingLinkDetector.detect(location: "", notes: "huddle here https://app.slack.com/huddle/T01/C02"))
        XCTAssertNotNil(MeetingLinkDetector.detect(location: "https://acme.webex.com/meet/room", notes: ""))
        XCTAssertNil(MeetingLinkDetector.detect(location: "Room 5", notes: "no link here at all"))
    }

    // MARK: - Hotkey dispatcher fake

    private final class FakeHotkeyRegistry: HotkeyRegistry {
        private(set) var registered: [HotkeyChord: () -> Void] = [:]
        var failNext = false
        func register(_ chord: HotkeyChord, handler: @escaping () -> Void) -> Bool {
            if failNext { failNext = false; return false }
            registered[chord] = handler
            return true
        }
        func unregister(_ chord: HotkeyChord) { registered[chord] = nil }
        /// Test helper: simulate the OS firing the chord.
        func fire(_ chord: HotkeyChord) { registered[chord]?() }
    }

    // MARK: - 11 (bonus, supports §4 §6). Hotkey dispatch + conflict detection

    func testHotkeyDispatcherBookkeepingAndConflicts() {
        let registry = FakeHotkeyRegistry()
        let dispatcher = HotkeyDispatcher(registry: registry)

        let chord = HotkeyChord(keyCode: 49, modifiers: [.command, .shift]) // ⌘⇧Space

        var fired = 0
        let result = dispatcher.bind(action: "toggle-vee", chord: chord) { fired += 1 }
        XCTAssertEqual(result, .registered)

        // Conflict: a different action wanting the same chord is rejected.
        let conflict = dispatcher.bind(action: "other", chord: chord) {}
        XCTAssertEqual(conflict, .conflict(existingAction: "toggle-vee"))

        // The dispatcher forwards an OS callback to the right action.
        registry.fire(chord)
        XCTAssertEqual(fired, 1)

        // Rebinding the same action to a new chord releases the old one.
        let chord2 = HotkeyChord(keyCode: 49, modifiers: [.option])
        XCTAssertEqual(dispatcher.bind(action: "toggle-vee", chord: chord2) { fired += 1 }, .registered)
        XCTAssertNil(registry.registered[chord], "old chord released on rebind")
        XCTAssertNotNil(registry.registered[chord2])

        // Now the original chord is free for "other".
        XCTAssertEqual(dispatcher.bind(action: "other", chord: chord) {}, .registered)
    }
}
