#!/usr/bin/env python3
"""Embed the TypeScript and Python SDK sources into the `vee` CLI.

A Vee plugin is a single executable dropped in a folder — no build step, no
package manager, no `node_modules`. So the SDK cannot be *imported* from
somewhere; it has to travel *with* the plugin as a sibling file. `vee new` and
`vee sdk` write that sibling, which means the CLI needs the SDK source inside
its own binary.

SwiftPM resources cannot reference files outside a target's directory, so the
sources are generated into a Swift file instead. This script writes it; run

    python3 scripts/embed_sdk.py            # regenerate
    python3 scripts/embed_sdk.py --check    # fail if stale (CI)

Go is deliberately absent: a Go plugin compiles to a binary, so it consumes the
SDK as a normal module rather than a vendored file.

Pure standard library, matching docs/scripts/.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "Sources/VeeCLI/EmbeddedSDK.swift")

SDKS = [
    ("typescript", "plugins/typescript/vee.ts", "vee.ts"),
    ("python", "plugins/python/vee.py", "vee.py"),
]


def raw_literal(text):
    """A Swift raw string literal with enough `#` to not collide with content."""
    hashes = 1
    while ('"""' + "#" * hashes) in text or ("#" * hashes + '"""') in text:
        hashes += 1
    pad = "#" * hashes
    return '%s"""\n%s\n"""%s' % (pad, text, pad)


def render():
    parts = [
        "// Generated by scripts/embed_sdk.py — DO NOT EDIT.",
        "//",
        "// The SDK sources, embedded so `vee new` and `vee sdk` can write the SDK",
        "// next to a plugin. A Vee plugin is a single executable with no build step,",
        "// so the SDK travels with it as a sibling file rather than being resolved",
        "// from a package manager.",
        "//",
        "// Regenerate with: python3 scripts/embed_sdk.py",
        "",
        "enum EmbeddedSDK {",
        "    /// The filename each language's SDK is written as, beside the plugin.",
        "    static func filename(for language: String) -> String? {",
        "        switch language {",
    ]
    for name, _, filename in SDKS:
        parts.append('        case "%s": return "%s"' % (name, filename))
    parts += [
        "        default: return nil",
        "        }",
        "    }",
        "",
        "    /// The SDK source for `language`, or nil when it does not vendor one.",
        "    static func source(for language: String) -> String? {",
        "        switch language {",
    ]
    for name, _, _ in SDKS:
        parts.append('        case "%s": return %s' % (name, name))
    parts += [
        "        default: return nil",
        "        }",
        "    }",
        "",
    ]
    for name, rel, _ in SDKS:
        with open(os.path.join(ROOT, rel), encoding="utf-8") as handle:
            body = handle.read().rstrip("\n")
        parts.append("    static let %s = %s" % (name, raw_literal(body)))
        parts.append("")
    parts.append("}")
    return "\n".join(parts) + "\n"


def main():
    generated = render()
    if "--check" in sys.argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != generated:
            print("Sources/VeeCLI/EmbeddedSDK.swift is stale: the SDK sources have\n"
                  "changed since it was generated, so `vee new` would vendor an old\n"
                  "copy of the SDK.\n\nRegenerate it: python3 scripts/embed_sdk.py")
            return 1
        print("ok: embedded SDK sources are current")
        return 0
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write(generated)
    print("wrote %s (%d KB)" % (os.path.relpath(OUT, ROOT), len(generated) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
