#!/usr/bin/env bash
# Publish (or refresh) the Vee Homebrew cask in navbytes/homebrew-tap so the tap
# always tracks the release the workflow just built. Idempotent and
# self-seeding: it creates Casks/vee.rb (and a tap README) on the first run and
# bumps version + sha256 on every run after.
#
# Runs from the Release workflow, which has Vee.zip in the working directory.
# Expects, in the environment:
#   HOMEBREW_TAP_TOKEN  fine-grained PAT with contents:write on navbytes/homebrew-tap
#   RELEASE_TAG         the release tag, e.g. v0.1.13
#
# The step is skipped when HOMEBREW_TAP_TOKEN is absent, so forks and
# unconfigured repos still release cleanly (the tap just isn't updated).
set -euo pipefail

: "${HOMEBREW_TAP_TOKEN:?HOMEBREW_TAP_TOKEN is required}"
: "${RELEASE_TAG:?RELEASE_TAG is required (e.g. v0.1.13)}"

if [ ! -f Vee.zip ]; then
  echo "::error::Vee.zip not found in $(pwd); run this after the Package step." >&2
  exit 1
fi

version="${RELEASE_TAG#v}"
sha="$(shasum -a 256 Vee.zip | awk '{print $1}')"
echo "Cask target: vee ${version} (sha256 ${sha})"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT
git clone --depth 1 \
  "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/navbytes/homebrew-tap.git" \
  "$workdir/tap"

tap="$workdir/tap"
mkdir -p "$tap/Casks"

cat > "$tap/Casks/vee.rb" <<EOF
cask "vee" do
  version "${version}"
  sha256 "${sha}"

  url "https://github.com/navbytes/vee/releases/download/v#{version}/Vee.zip",
      verified: "github.com/navbytes/vee/"
  name "Vee"
  desc "Native macOS menu-bar script runner, compatible with xbar and SwiftBar plugins"
  homepage "https://github.com/navbytes/vee"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Apple Silicon + macOS 26 (Tahoe) or later, matching the app's requirements.
  depends_on arch: :arm64
  depends_on macos: ">= :tahoe"

  app "Vee.app"

  zap trash: [
    "~/Library/Application Support/Vee",
    "~/Library/Preferences/com.vee.app.plist",
  ]
end
EOF

# Seed a README on a fresh tap so the repo explains itself. Never overwritten,
# so any hand-edits to the tap's README are preserved.
if [ ! -f "$tap/README.md" ]; then
  cat > "$tap/README.md" <<'EOF'
# navbytes/homebrew-tap

Homebrew tap for [Vee](https://github.com/navbytes/vee), a native macOS menu-bar
script runner.

```sh
brew tap navbytes/tap
brew install --cask vee
```

`brew upgrade --cask vee` picks up new releases automatically.

## Notes

- Requirements match the app: **Apple Silicon** and **macOS 26 (Tahoe) or later**.
- `Casks/vee.rb` is generated by Vee's release workflow
  ([`scripts/update-homebrew-cask.sh`](https://github.com/navbytes/vee/blob/main/scripts/update-homebrew-cask.sh))
  on every release — edit that script, not the cask here.
EOF
fi

cd "$tap"
if git diff --quiet; then
  echo "Tap already up to date for ${version}; nothing to push."
  exit 0
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add -A
git commit -m "vee ${version}"
git push
echo "Pushed tap update for vee ${version}."
